### ISSUE TITLE
思源2.0.3版本嵌入块与代码块的连线问题

### ISSUE THREAD

**Issue by HowcanoeWang** [royc01/notion-theme#10]
印象里之前是修复的没啥问题，但是更新了之后，可能思源又自己改css了：

嵌入块的效果：

![image](https://user-images.githubusercontent.com/19968935/166403232-a6ac565c-d9f9-4aaf-ad76-6df3711a534a.png)

代码块的效果：

![image](https://user-images.githubusercontent.com/19968935/166403280-58a3beb5-83ce-4e3f-9ca6-25040652df24.png)

思源2.0.3，notion主题2.0.2

**Comment by royc01** [comment]
![22](https://user-images.githubusercontent.com/38906705/166411199-1f1ef78a-ff89-44e0-b3fc-eafa7de0802d.jpg)

我这边嵌入块正常，代码块下个版本修复
