### ISSUE TITLE
Savor找不到附加的几个按钮了

### ISSUE THREAD

**Issue by winter60** [royc01/notion-theme#100]
![image](https://user-images.githubusercontent.com/23653326/201531396-6adb7c5e-98d6-471f-b3e5-f18940a36b5e.png)
![image](https://user-images.githubusercontent.com/23653326/201531401-959839bb-c662-4622-b5c3-74c00e12da50.png)
重启无效，不知道怎么解决所以来问下

**Comment by GentooXu** [comment]
> ![image](https://user-images.githubusercontent.com/23653326/201531396-6adb7c5e-98d6-471f-b3e5-f18940a36b5e.png) ![image](https://user-images.githubusercontent.com/23653326/201531401-959839bb-c662-4622-b5c3-74c00e12da50.png) 重启无效，不知道怎么解决所以来问下
![image](https://user-images.githubusercontent.com/39244046/201532110-513abfc9-3367-4ded-87fe-382fa94e27f3.png)
重置一下试试。

**Comment by winter60** [comment]
> ![image](https://user-images.githubusercontent.com/39244046/201532110-513abfc9-3367-4ded-87fe-382fa94e27f3.png) 重置一下试试。

可以了，谢谢老铁了，这么神奇的吗
