### ISSUE TITLE
嵌入块与普通段落款区别不明显，建议优化

### ISSUE THREAD

**Issue by intelion2022** [royc01/notion-theme#101]
下图上方是嵌入块，下方是普通段落块，仔细看才能看到嵌入块左侧一条细线，和普通段落块不好区分，建议优化。
![image](https://user-images.githubusercontent.com/116488969/201549794-c4c77905-bcfe-4af6-be12-bd5538b3d3b9.png)

**Comment by royc01** [comment]
下个版本修复
