### ISSUE TITLE
引用文档 设置行内格式（加粗、斜体等）字体颜色会变成默认主题的颜色

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#103]
![image](https://user-images.githubusercontent.com/39244046/201644431-d25adc66-53bc-4380-85bb-7d25cb12815a.png)

**Comment by royc01** [comment]
没看懂

**Comment by GentooXu** [comment]
![image](https://user-images.githubusercontent.com/39244046/201646609-dad7da1d-1855-447b-8702-d181db42a904.png)

**Comment by CFmeinz** [comment]
> ![image](https://user-images.githubusercontent.com/39244046/201646609-dad7da1d-1855-447b-8702-d181db42a904.png)

  是的 我也有此问题

**Comment by CFmeinz** [comment]
是的 我也有此问题

**Comment by GentooXu** [comment]
我更新了3.0.8，块引用的问题解决了，但是虚拟引用出问题了，虚拟引用和块引用变成一样的样式了，datatype*=block-ref 会匹配到 virtual-block-ref 。

**Comment by royc01** [comment]
> 我更新了3.0.8，块引用的问题解决了，但是虚拟引用出问题了，虚拟引用和块引用变成一样的样式了，datatype*=block-ref 会匹配到 virtual-block-ref 。

感谢反馈
