### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by intelion2022** [royc01/notion-theme#104]
加粗的文字转换为标题，标题颜色不起作用，均为黑色~

**Comment by royc01** [comment]
可以录屏看看么

**Comment by intelion2022** [comment]
![20221116-140351](https://user-images.githubusercontent.com/116488969/202097353-825c8521-dc7b-45b4-8911-a15eb83f7759.gif)

**Comment by intelion2022** [comment]
录了个gif文档，传不上去。我在描述一下：写一个段落块文字，选中后按Ctrl+B，把文字加粗；选中块，转换为“一级标题”，这时标题颜色是黑色的，不是红色的。如果段落块文字不加粗，直接转换为“一级标题”，则标题文字的颜色是红色的。

**Comment by royc01** [comment]
了解，是sugar主题的问题

**Comment by Spetor** [comment]
借个楼问一下，怎么更新之后主题只有明亮和黑暗了
![image](https://user-images.githubusercontent.com/63890541/202115357-a218c8b3-1617-4bd6-ade8-0891cbb44059.png)

**Comment by royc01** [comment]
> 借个楼问一下，怎么更新之后主题只有明亮和黑暗了 ![image](https://user-images.githubusercontent.com/63890541/202115357-a218c8b3-1617-4bd6-ade8-0891cbb44059.png)

没加载成功，设置-外观-恢复默认  试试

**Comment by Spetor** [comment]
![image](https://user-images.githubusercontent.com/63890541/202125571-62136b6f-3237-4d5e-831c-c7ea94e72637.png)
恢复默认主题变回之前的了，但是选项还是没得选呢

**Comment by royc01** [comment]
在放大镜左侧

**Comment by Spetor** [comment]
> 在放大镜左侧
明白了，感谢
