### ISSUE TITLE
平板端&手机端适配

### ISSUE THREAD

**Issue by Timelesseternity** [royc01/notion-theme#109]
最新版的主题，在平板上不适配：比如搜索按钮没有。原来的notion主题就有。
![image](https://user-images.githubusercontent.com/108171881/202903386-ce788128-eba6-49c2-917f-a582e42bf196.png)
原notion主题:
![image](https://user-images.githubusercontent.com/108171881/202903408-988a8fd9-8ee9-4115-bdee-614917f49f9e.png)
手机端的问题：
![image](https://user-images.githubusercontent.com/108171881/202903437-9fe3b9a0-4a5e-44b4-b8d8-075122219e5e.png)
以及文档树那一行挡住了一个笔记本：
![image](https://user-images.githubusercontent.com/108171881/202903476-29f16b88-dfbc-4384-8d24-ef0d0437e393.png)
还有，似乎移动端没有面包屑，这样就找不到上传图片、查看字数等的功能了

**Comment by royc01** [comment]
新版适配
