### ISSUE TITLE
bug：隐藏按钮后点大纲跳转内容，会导致界面整体上移

### ISSUE THREAD

**Issue by o-ut-man** [royc01/notion-theme#110]
界面上移后导致顶部内容跑到显示区域以外了。
需要切换主题才能恢复。 
取消隐藏按钮没出现问题。

![image](https://user-images.githubusercontent.com/34265164/203931770-22169783-a86d-438f-b847-a0b1aafaa553.png)

**Comment by royc01** [comment]
我这边没测试出来，可以录屏么

**Comment by royc01** [comment]
之前的版本有过这样的问题，修复过了，或者更新一下版本看看？

**Comment by royc01** [comment]
没有问题先关闭了
