### ISSUE TITLE
文档树中，有无子页面的文档似乎没有对齐

### ISSUE THREAD

**Issue by SsparKluo** [royc01/notion-theme#113]
![image](https://user-images.githubusercontent.com/32617864/204436608-b1e9d8a3-4000-40fa-b976-f3328837ef2e.png)

**Comment by royc01** [comment]
是最新版本么

**Comment by SsparKluo** [comment]
> 是最新版本么

是的

**Comment by royc01** [comment]
![QQ截图20221129154657](https://user-images.githubusercontent.com/38906705/204469351-2548bb78-481b-4a4a-bbca-70598e274536.jpg)
我这边是正常的

**Comment by SsparKluo** [comment]
好像是因为用代码片段改了字体就有问题了...但是别的主题和初始主题没问题....我再看看

**Comment by SsparKluo** [comment]
> 好像是因为用代码片段改了字体就有问题了...但是别的主题和初始主题没问题....我再看看

确实是这个问题....

**Comment by SsparKluo** [comment]
> > 好像是因为用代码片段改了字体就有问题了...但是别的主题和初始主题没问题....我再看看
> 
> 确实是这个问题....

也许可以用 svg 来画这个点？

**Comment by royc01** [comment]
> > > 好像是因为用代码片段改了字体就有问题了...但是别的主题和初始主题没问题....我再看看
> > 
> > 
> > 确实是这个问题....
> 
> 也许可以用 svg 来画这个点？

用字符可以提升一点性能，或者后面我直接用背景色填充吧

**Comment by SsparKluo** [comment]
> > > > 好像是因为用代码片段改了字体就有问题了...但是别的主题和初始主题没问题....我再看看
> > > 
> > > 
> > > 确实是这个问题....
> > 
> > 
> > 也许可以用 svg 来画这个点？
> 
> 用字符可以提升一点性能，或者后面我直接用背景色填充吧

OK的，还是以性能为重吧hhh
