### ISSUE TITLE
导出成PDF时，大纲笔记前面的点都消失掉了，请优化下

### ISSUE THREAD

**Issue by henmy168** [royc01/notion-theme#114]
很爱这个主题
但是我导出成PDF时，大纲的点就消失了，导出的pdf界面似乎也没在思源笔记里的好看
导出图片就没这个问题
特意注册账号来反馈，请优化下，谢谢。
![2](https://user-images.githubusercontent.com/119473176/204708357-31dac4cd-278b-450f-b3b9-27e8c38ed9a5.png)

**Comment by henmy168** [comment]
我切换到默认主题，导出PDF,大纲的点是存在的。

**Comment by royc01** [comment]
好的，感谢反馈

**Comment by royc01** [comment]
该问题在思源2.5.3版本解决
https://github.com/siyuan-note/siyuan/pull/6741

**Comment by henmy168** [comment]
已经修复了，感谢
