### ISSUE TITLE
需求：增加小窗模式

### ISSUE THREAD

**Issue by lentikr** [royc01/notion-theme#115]
有时需要边看视频边做笔记，这种情况下我一般会隐藏两侧功能栏，再缩小窗口尺寸。但体验感觉还是不太好。
但希望在这种情况下诸如顶栏、底部状态栏等部分可以不显示。
能否通过主题实现如下功能：
在主题设置中（即与“隐藏按钮”所在的顶栏菜单）添加一项“小窗模式”，开启后仅保留页签列表、编辑器界面和一个退出小窗模式的按钮，其它功能一律隐藏，仅在退出小窗模式后才可显示。大致如下图。
![image](https://user-images.githubusercontent.com/95539012/205532099-3f516741-3d1a-489a-94bd-e9d224d17c0d.png)

**Comment by royc01** [comment]
先用alt y顶顶，就是没有页签，加功能后面再考虑😅

**Comment by royc01** [comment]
现在可以用拖出窗口实现，关闭了
