### ISSUE TITLE
导出图片 项目符号显示不正常

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#117]
![image](https://user-images.githubusercontent.com/39244046/205677332-41df70bd-a383-4bfc-a050-c11171838cfa.png)

**Comment by GentooXu** [comment]
我是SiYuan 2.5.3-dev2，应该是最新了，主题也重新下载，并重置了外观设置，导出图片还是不正常。

**Comment by royc01** [comment]
好的，我再调一下
