### ISSUE TITLE
视频时间戳功能

### ISSUE THREAD

**Issue by EdwinWang0508** [royc01/notion-theme#119]
能否实现B站视频时间戳功能，感谢大佬

**Comment by HowcanoeWang** [comment]
> 能否实现B站视频时间戳功能，感谢大佬

你在B站视频链接后面，增加一个?t=600，600是跳转的秒数就可以了

https://www.bilibili.com/video/BV1yD4y1V7fd/?t=300

但是缺点好像是，打开页面会自动播放

**Comment by royc01** [comment]
插件实现
