### ISSUE TITLE
graphviz的图片是黑色的

### ISSUE THREAD

**Issue by metadaoge** [royc01/notion-theme#13]
如题，light主题下生成的图是暗色的，黑色模式下是白色的。是我哪里操作不当吗
![image](https://user-images.githubusercontent.com/70755994/170998540-2213a9bb-d4dd-42de-b64d-d20cb476b2d8.png)

**Comment by royc01** [comment]
感谢反馈，应该是主题出错了，想不到有人用Graphviz，我下个版本修复，嘿嘿
