### ISSUE TITLE
表格顏色錯誤。

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-theme#133]
表格中有顏色。

![image](https://user-images.githubusercontent.com/90691302/210674931-ff3a85d7-f4cf-4ce0-a5ea-05a39c8ddb3e.png)

垂直模式
![image](https://user-images.githubusercontent.com/90691302/210674965-b4a0e1c3-d3cd-4b13-9740-87a7e74de1aa.png)

**Comment by royc01** [comment]
感谢反馈，下个版本修复，但最近没啥时间，要等一阵
