### ISSUE TITLE
有序列表嵌套无序列表，无序列表的圆点消失。

### ISSUE THREAD

**Issue by ytin16** [royc01/notion-theme#134]
如下图所示，第 3 层嵌套的是无序列表，无序列表的圆点消失。

![image](https://user-images.githubusercontent.com/23134413/210723235-37695396-5b85-46de-b608-ca14be9b5121.png)

**Comment by royc01** [comment]
https://github.com/royc01/notion-theme/issues/128
有同样的issue了，但最近没啥时间更新，要等一下
