### ISSUE TITLE
希望可以加入LiquidText BookxNote的链接图标，谢谢

### ISSUE THREAD

**Issue by holduan** [royc01/notion-theme#137]
![LiquidText](https://user-images.githubusercontent.com/80377040/212547262-41271855-ca26-4e8a-885a-d57e0ece7f23.png)
![LargeTile scale-100](https://user-images.githubusercontent.com/80377040/212547268-08cbe768-3b5b-4ef9-941b-67a354edab8c.png)
![BookxNotePro](https://user-images.githubusercontent.com/80377040/212547276-4d670e38-750b-4f5e-b07b-472af866d5ef.png)

**Comment by royc01** [comment]
感谢反馈，下个版本加入
