### ISSUE TITLE
2.7版本，浏览器中查看，图标位置偏移

### ISSUE THREAD

**Issue by HowcanoeWang** [royc01/notion-theme#138]
![image](https://user-images.githubusercontent.com/19968935/212911569-dfb05634-527c-4063-b624-c64d1c042f00.png)

![image](https://user-images.githubusercontent.com/19968935/212911616-b9752c8b-bd3a-4efe-9402-bc131ada462c.png)

**Comment by royc01** [comment]
这个后面再适配

**Comment by aobatu** [comment]
我用的Mac上也是偏移的，这个到时候也是一起适配吗？

**Comment by MistRay** [comment]
Mac版本也是偏移的，请问有一块适配的计划么？

**Comment by royc01** [comment]
手头上没有mac设备，后面再慢慢适配吧

**Comment by bobo0810** [comment]
mac版2.7.1版本  存在同样问题
![image](https://user-images.githubusercontent.com/26057879/215696688-08f3ffd8-5da4-4c13-b708-7418d9bb4fd6.png)
