### ISSUE TITLE
How to use "progress bar"?

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-theme#139]
伙計，那麼你可以結束這個對話了。 但是如何使用“進度”功能呢？ 你能給我指一個視頻嗎？ 或者在這裡快速解釋一下？

![image](https://user-images.githubusercontent.com/90691302/212919917-50fec43d-c928-4312-8391-6b446bc829d0.png)

**Comment by royc01** [comment]
the fourth one

**Comment by taozina0587** [comment]
是的。 但是我該如何使用它呢？

**Comment by royc01** [comment]
![Animation](https://user-images.githubusercontent.com/38906705/212922473-0764fc16-8f81-4fd6-828f-a162dd8c9f22.gif)

**Comment by taozina0587** [comment]
現在我明白瞭如何格式化要使用的文本。 非常感謝你。

**Comment by royc01** [comment]
no problem
