### ISSUE TITLE
弱化顶栏按钮

### ISSUE THREAD

**Issue by heimi98** [royc01/notion-theme#142]
感觉顶栏的按钮存在感太强了，分散了注意力
![image](https://user-images.githubusercontent.com/56879067/214479257-da5efd1f-5169-4dba-bba2-9df04c66dfde.png)

对比侧栏的按钮
![image](https://user-images.githubusercontent.com/56879067/214479306-f926fca2-7f49-4374-98f6-f9ed1aaae3dd.png)

甚至比文档树的字体还粗
![image](https://user-images.githubusercontent.com/56879067/214479355-cf4d4348-c9f3-46ef-b23e-55105e849cc8.png)

不太想选择“隐藏按钮”，会造成操作不方便。建议弱化一下顶栏按钮。谢谢。

**Comment by royc01** [comment]
感谢反馈，顶栏功能比较重要，暂时不会改了，可以使用右上角隐藏按钮的功能顶顶
