### ISSUE TITLE
字数统计的颜色可以改回来吗？

### ISSUE THREAD

**Issue by chjchen** [royc01/notion-theme#144]
3.22字数统计的颜色可以改回来吗？

**Comment by royc01** [comment]
应该不会改了，调淡了整体和谐一点，如果需要原来的颜色可以尝试添加以下css代码片段

.status__counter:not(:empty){
	background-color:var(--b3-theme-primary)!important;
	color:#fff!important;
}
.status__counter:not(:empty) span{
	color:#fff!important;
}

**Comment by chjchen** [comment]
谢谢
