### ISSUE TITLE
标题层级提示符号消失

### ISSUE THREAD

**Issue by 2016201256** [royc01/notion-theme#146]
之前标题后面有那些小点点表明层级, 不知道为什么现在没有了, 想请问下是取消了吗, 还是我个人设置的问题~ 感谢!

**Comment by lentikr** [comment]
我这儿还是存在的。看看是不是CSS片段的问题？或者重置一下外观

**Comment by 2016201256** [comment]
找到原因了, 开启拼写检查的时候符号就消失了, 关闭拼写检查就又显示了. 希望能够修复一下

**Comment by royc01** [comment]
感谢反馈
