### ISSUE TITLE
面板悬浮后没有触发自适应宽度调整，但拖动改变窗口大小可以

### ISSUE THREAD

**Issue by lentikr** [royc01/notion-theme#148]
逻辑上的问题在于当编辑区域的宽度一致时，“触发自适应宽度调整”这一行为的表现不一致。
![动画](https://user-images.githubusercontent.com/95539012/216219414-96717d92-5829-428b-a09c-3b1abf34a41f.gif)

**Comment by royc01** [comment]
官方做了，可以关闭了
