### ISSUE TITLE
PDF视图页面与文档页面边界难以捕获到调整左右布局的手柄

### ISSUE THREAD

**Issue by youth54** [royc01/notion-theme#149]
感谢作者提供这么精美的主题，我在使用过程中发现，如下图所示的位置，难以捕获到左右页面调整布局手柄。
而使用默认主题没有这个问题。希望能修复一下，谢谢~~

![image](https://user-images.githubusercontent.com/72968849/216637139-0832a9cf-9c53-4a02-a0b2-5ae947a6ef38.png)

**Comment by royc01** [comment]
这个地方应该没改过的，是最新版么

**Comment by youth54** [comment]
> 这个地方应该没改过的，是最新版么

用的是v3.2.2版本。刚才打开了软件试了一下，又好了，又容易捕捉了。😂
