### ISSUE TITLE
新建日记配置更改后, 通过日历不能定位

### ISSUE THREAD

**Issue by HappyJamesL** [royc01/notion-theme#151]
![image](https://user-images.githubusercontent.com/12409317/217690704-439ff4e8-cf67-4b0c-9327-02373868816b.png)
![image](https://user-images.githubusercontent.com/12409317/217691960-46e03421-5636-4e6a-bcfa-0b2011bc17c0.png)

如图所示, 修改新建日记的配置, 通过ALT+5, 可以正确新建日记, 通过日历只能到月份这一层的文档

**Comment by royc01** [comment]
暂时只支持识别默认路径
