### ISSUE TITLE
钉住按钮颜色异常

### ISSUE THREAD

**Issue by lentikr** [royc01/notion-theme#153]
![image](https://user-images.githubusercontent.com/95539012/218956798-f63f9c4a-e4c2-4a4c-a246-c07a8cfc6561.png)
![image](https://user-images.githubusercontent.com/95539012/218956884-e414eee2-78aa-4062-ad15-2f37ef8fef97.png)

**Comment by royc01** [comment]
是的，不知道官方还换不换位置，所以先不处理

**Comment by royc01** [comment]
新版没有问题了，关闭了
