### ISSUE TITLE
字体颜色渲染错误

### ISSUE THREAD

**Issue by GoseRank** [royc01/notion-theme#156]
主题版本：3.2.6
siyuan版本：2.7.7（2.7.6也有这个问题）

问题描述：使用Savor主题时**标红**的部分，切换到其他主题后无法阅读
![不可看](https://user-images.githubusercontent.com/53933742/221851823-92ea183f-0bab-4cc7-8efe-d7b22d87d822.png)

问题原因（自己猜的）：Savor主题的字体颜色渲染顺序，与官方主题不一致。
![字体颜色顺序](https://user-images.githubusercontent.com/53933742/221852346-e88e8540-23b7-479a-85ed-143d8d5841ee.png)

其他测试（确实影响阅读）：
![屏幕截图 2023-02-28 202237](https://user-images.githubusercontent.com/53933742/221853209-0792cffa-608c-4d4a-9338-6ae02882ee29.png)

总结：官方主题下标红的字，在Savor主题下颜色显示异常。Savor主题下标红的字，其他主题没法阅读

**Comment by royc01** [comment]
一开始做的时候是按颜色顺序重新排列了，现在改的话之前的文档也会显示颜色不一样，建议用代码片段调整自己想要的颜色顺序

**Comment by GoseRank** [comment]
感谢，已通过修改代码解决❤️
