### ISSUE TITLE
请求IOS端适配

### ISSUE THREAD

**Issue by LeeOswald368** [royc01/notion-theme#157]
![9cecb9650cc5ba7f9bc31f3146d26ae](https://user-images.githubusercontent.com/120121713/222954346-99e633d3-ff6f-4aeb-8dd9-776dab20d698.jpg)
![94d7ae44819c6f3b742867537b8dcaf](https://user-images.githubusercontent.com/120121713/222954359-ab4088b2-63a2-4117-80d2-67f0e582e590.jpg)
很喜欢该主题，想在手机端使用，但这个问题，从去年就一直存在。希望能够得到适配。

**Comment by royc01** [comment]
最新版本的手机端应该适配了，麻烦更新一下看看

**Comment by LeeOswald368** [comment]
> 最新版本的手机端应该适配了，麻烦更新一下看看

已更新最新版本，发现已经解决。但是还有一个地方，我上次忘记说明了。
![7a05c8604b2706f566f00e419e007b9](https://user-images.githubusercontent.com/120121713/223350455-5ac62415-a814-4137-a056-67f4213e0405.jpg)
这里是没有对齐的

**Comment by royc01** [comment]
![image](https://user-images.githubusercontent.com/38906705/223351764-4349ffe0-4a83-4a8e-a64a-bbf07f52ab97.png)
重开一下看看，我这边貌似正常

**Comment by LeeOswald368** [comment]
> ![image](https://user-images.githubusercontent.com/38906705/223351764-4349ffe0-4a83-4a8e-a64a-bbf07f52ab97.png) 重开一下看看，我这边貌似正常

我这边依然还是这样的状况。而且，在ios端下，暗黑模式不起作用。

**Comment by royc01** [comment]
![Screenshot_2023-03-07-20-21-11-464-edit_org b3log](https://user-images.githubusercontent.com/38906705/223420697-2397825d-a78a-4783-a371-c0a908db3ac5.jpg)
确认是这样选择么？

**Comment by LeeOswald368** [comment]
> ![Screenshot_2023-03-07-20-21-11-464-edit_org b3log](https://user-images.githubusercontent.com/38906705/223420697-2397825d-a78a-4783-a371-c0a908db3ac5.jpg) 确认是这样选择么？

是的。
![683af2bb6f7b9f5086b6af8493be60c](https://user-images.githubusercontent.com/120121713/223421362-d681476f-bcdb-48d2-8f03-a3310d37c4b9.jpg)
![66b16f71dccaaf0be04ea3cb1211ca8](https://user-images.githubusercontent.com/120121713/223421387-7557a8a0-f554-4483-9247-653e16123cbd.jpg)

Ios系统为16.3.1，软件版本为2.7.7

**Comment by royc01** [comment]
好吧，我再看看😅
