### ISSUE TITLE
新窗口跟随主界面的 salt 界面配色

### ISSUE THREAD

**Issue by XinLi0111** [royc01/notion-theme#158]
主题非常漂亮，一直在用，但是最近在用的时候发现新窗口的颜色太亮了，和主界面的护眼 salt 配色反差比较明显。希望能继承主界面的配色。另外新窗口右上角的图标似乎有点错位

**Comment by royc01** [comment]
下个版本修复

**Comment by XinLi0111** [comment]
好的，感谢费心尝试了。

**Comment by XinLi0111** [comment]
看起来另一个主题作者实现了，辛苦试试看？ https://github.com/Achuan-2/siyuan-themes-tsundoku/issues/69

**Comment by royc01** [comment]
3.4.1支持
