### ISSUE TITLE
是否可以取消窗口的滚动条？

### ISSUE THREAD

**Issue by aobatu** [royc01/notion-theme#16]
使用的是v2.2.2版本，发现窗口的右边有个竖向的滚动条，如果往下拉会隐藏了标签页，有好几次我还以为标签页丢失了。
不知道这是一个bug还是就是主题的特性，所以，想问下如果要取消这个滚动条，有什么办法不？

<img width="394" alt="image" src="https://user-images.githubusercontent.com/24941288/177046552-3adc6fdf-179f-47c2-bca7-3e3142ac75ac.png">

**Comment by royc01** [comment]
应该是bug，但我这边暂时重现不了，是否用高分屏的？

**Comment by TankNee** [comment]
<img width="1986" alt="image" src="https://user-images.githubusercontent.com/43956168/178207977-2cee0214-2da8-4ef3-b996-2fe5186667ec.png">
我这也有这个问题。
我的机器是MacBook Pro 14，显示器分辨率为4k，27寸

**Comment by royc01** [comment]
> <img alt="image" width="1986" src="https://user-images.githubusercontent.com/43956168/178207977-2cee0214-2da8-4ef3-b996-2fe5186667ec.png">
> 
> 我这也有这个问题。 我的机器是MacBook Pro 14，显示器分辨率为4k，27寸

是最新版的主题吗？怎么触发的呢

**Comment by TankNee** [comment]
> > <img alt="image" width="1986" src="https://user-images.githubusercontent.com/43956168/178207977-2cee0214-2da8-4ef3-b996-2fe5186667ec.png">
> > 我这也有这个问题。 我的机器是MacBook Pro 14，显示器分辨率为4k，27寸
> 
> 是最新版的主题吗？怎么触发的呢

是最新版的主题，只要应用主题就会出现这个问题，我猜应该是哪里高度算错了。

**Comment by royc01** [comment]
> 

好的，我再调整一下看看

**Comment by royc01** [comment]
新版已经上线了，麻烦测试一下

**Comment by TankNee** [comment]
多出来的那个滚动条确实没了，但是底部的图标还是有点违和。
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/43956168/180118929-1034eb7b-f157-4355-8a07-e3a765bdb238.png">

**Comment by royc01** [comment]
> 多出来的那个滚动条确实没了，但是底部的图标还是有点违和。 <img alt="image" width="1648" src="https://user-images.githubusercontent.com/43956168/180118929-1034eb7b-f157-4355-8a07-e3a765bdb238.png">
![QQ截图20220721110833](https://user-images.githubusercontent.com/38906705/180121525-dd9f448d-1277-4cf2-8b64-4cbfe873355f.jpg)
应该是这样的。。。这就有点懵了
