### ISSUE TITLE
自从恢复顶栏样式后，觉得不简洁了，能把顶栏的这个位置去掉吗

### ISSUE THREAD

**Issue by henmy168** [royc01/notion-theme#161]
大神好，一直用这个主题很久了，为了反馈特意注册
可否把顶栏我标红的这行标题给隐藏吗，右侧的主题的按钮放哪都可以。
实在感觉标红的位置有些突兀，下面已经有标题了，上面还要显示一个大大的标题，不好看。强烈希望隐藏标红的这部分
![image](https://user-images.githubusercontent.com/119473176/224549597-a8b0c522-fc2f-41a7-a275-3cfd06fda8d4.png)
谢谢

**Comment by henmy168** [comment]
上面那个一行重复显示的标题，感觉太不简洁了，之前的主题显示方式就很好，很有美感
来自一个强迫症的呼声

**Comment by royc01** [comment]
暂时不改了，先用隐藏顶栏的功能顶顶，后面有更好的方案再优化

**Comment by henmy168** [comment]
> 暂时不改了，先用隐藏顶栏的功能顶顶，后面有更好的方案再优化

隐藏顶栏的功能在哪，我翻了几遍，都没在设置中找到

**Comment by royc01** [comment]
顶栏 放大镜前面

**Comment by henmy168** [comment]
> 顶栏 放大镜前面

主题自带的功能，功能强大，666
