### ISSUE TITLE
请求移动端表格优化

### ISSUE THREAD

**Issue by LeeOswald368** [royc01/notion-theme#162]
移动端主题，表格是挤在一起的。无法左右滑动，软件默认主题可以。当表格项足够长和足够多的时候，挤在一起阅读困难。

**Comment by YorickGu** [comment]
同问，宽表全部挤在一起真的不好看

**Comment by royc01** [comment]
v3.3.0 修正

**Comment by YorickGu** [comment]
PC端也是这样，麻烦可以不要这样吗

**Comment by royc01** [comment]
> PC端也是这样，麻烦可以不要这样吗

pc端应该不会挤在一起，主要是可以直接看完整的内容，如果不需要换行可以用  块标-视图选择-不换行
