### ISSUE TITLE
能否做一个暗黑模式下的灰色背景版本？

### ISSUE THREAD

**Issue by hopebird** [royc01/notion-theme#163]
Savor浅色主题很好看，但现在的暗黑模式下Vineger主题是纯黑色的，对比度太高，比较刺眼，工作时间长了很累。希望能做一个柔和一点背景的，类似Workflowy默认主题那样的，或者借鉴vscode的配色。

**Comment by hopebird** [comment]
> 

按你说的做了，在一瞬间是个灰色的背景，然后又变成亮色背景了

**Comment by royc01** [comment]
不要选择顶栏任何的主题喔

**Comment by hopebird** [comment]
> 不要选择顶栏任何的主题喔
终于搞定了

**Comment by royc01** [comment]
可以👍，后面再优化一下这个主题选择的机制
