### ISSUE TITLE
长按键盘某键，会卡顿。包括退格键，动画会看不见。

### ISSUE THREAD

**Issue by youngerruan** [royc01/notion-theme#165]
1. 例如英文状态下长按A，A出现不是连续的，会卡顿
2. 比如想删除一段话，长按退格键会卡住，松开退格键会删除了很多字，估计是动画消失了。

以上问题，官方主题测试正常，所以猜测是bug~望修复，谢谢，很喜欢这个主题~~~

**Comment by royc01** [comment]
好的，下个版本会进行优化

**Comment by youngerruan** [comment]
感谢您，祝您生活上一切愉快～
2023年3月18日 +0800 17:35 royc01 ***@***.***>，写道：
