### ISSUE TITLE
几个月没用这么好看了

### ISSUE THREAD

**Issue by AugustTuan** [royc01/notion-theme#166]
大佬给力啊。 
这个颜值完全不逊色obsidian了
👍👍👍👍👍👍👍👍👍👍

**Comment by AugustTuan** [comment]
就是我这个看板里面嵌套表格以后，总感觉是个斜着的🤣
![image](https://user-images.githubusercontent.com/37429029/227086231-8fcb0d7a-ec2c-4ff0-92d6-37b5cdc2bd9a.png)

**Comment by royc01** [comment]
感谢支持，看板不支持嵌套，建议不要这么用

**Comment by AugustTuan** [comment]
> 感谢支持，看板不支持嵌套，建议不要这么用

其实现在也可以正常使用，就是样式有点奇怪， 
因为看板嵌套表格以后，非常节省空间，纵向和横向的空间都利用起来了。

我是从dark+切换过来的，dark+看起来比较整齐
![image](https://user-images.githubusercontent.com/37429029/227087321-8a1d6f14-f6cf-4d29-a4b6-35973aba46e1.png)

**Comment by AugustTuan** [comment]
另外还有一个疑问，就是这个第一列的长度有办法调整吗？怎么让第一列在一行显示？
![image](https://user-images.githubusercontent.com/37429029/227087696-037fdce6-d4fc-420c-9f42-8656f959d4dd.png)
