### ISSUE TITLE
暗黑模式下选项菜单显示异常

### ISSUE THREAD

**Issue by LeeOswald368** [royc01/notion-theme#168]
![image](https://user-images.githubusercontent.com/120121713/227573814-adb2fb35-9382-4359-b8bc-36926ddbcb07.png)

![image](https://user-images.githubusercontent.com/120121713/227574120-ff8db748-d113-4c8a-8278-3af3f84fb960.png)
这里没有对齐，手机端比较明显一点

**Comment by royc01** [comment]
下个版本修复
