### ISSUE TITLE
任务列表完成后划线样式调整建议

### ISSUE THREAD

**Issue by aobatu** [royc01/notion-theme#169]
首先非常感谢作者开发这么好的主题！

有个小小的建议，不知道是否可优化？
现状：针对任务列表，完成后划线会将这个任务下的所有内容划线。
期望：任务列表完成后，只针对任务本身划线，而不对下面的内容划线。
原因：很多场景下，任务列表下面的内容，是对这个任务的补充，和当下完成情况的总结，这些内容用划线的方式，就会容易被忽略，视觉不明显。

![image](https://user-images.githubusercontent.com/24941288/227682405-2c8345dc-3eb4-4660-9ac5-8c31d3d1f885.png)

若无法修改此样式，是否可告知有什么办法自定义实现呢？例如修改主题文件的方式实现。由于个人对样式的内容不了解，还望能给予指导。
再次表达感谢~

**Comment by royc01** [comment]
下个版本更新
