### ISSUE TITLE
窗口变小后搜索布局问题

### ISSUE THREAD

**Issue by Timelesseternity** [royc01/notion-theme#17]
作者您好。非常喜欢您的这一款主题。但是一旦思源的窗口变小后，用搜索功能就会呈现下图的界面，不能呈现关键词所在的块，不是很方便。
![image](https://user-images.githubusercontent.com/108171881/179128363-7f8e992f-c590-4910-8c23-b9ff22c435f2.png)
不像思源全屏后一样。全屏后有左边选择的的一竖排，如下图。
![image](https://user-images.githubusercontent.com/108171881/179128717-5fa50cee-faa1-455b-a067-9fccecd9b6da.png)
我记得以前最小化思源的时候，使用查找后，呈现的布局不是像现在这样子的。是特地这样设计的吗？能否给出一个解决方案，使得小窗思源后，使用查找功能，仍可以呈现所在文字的块，像官方的主题这样？
![image](https://user-images.githubusercontent.com/108171881/179129341-73f8c57c-931e-4333-82e5-c851ce053db0.png)

**Comment by royc01** [comment]
![1111](https://user-images.githubusercontent.com/38906705/179130790-ac435dc2-3a3f-4804-bce9-eb12ebb704c9.jpg)
缩小应该是这样的，或者高分屏出错吧，我再调整一下

**Comment by Timelesseternity** [comment]
作者您好。最新版的主题依然存在该问题。一旦把窗口压缩的比较窄（分屏做笔记）就会出现这个问题。能否继续优化下？谢谢作者。

**Comment by royc01** [comment]
啊。。调整过了，而且我这边显示也正常，要不你直接QQ找我吧，我替你看看，我是群里管理员Rc
