### ISSUE TITLE
评论选项经常消失

### ISSUE THREAD

**Issue by Yuminis98** [royc01/notion-theme#171]
笔记经常用着用着就没有评论这个功能了
![image](https://user-images.githubusercontent.com/117956441/227950461-1378780c-2dfc-4bae-bf76-debea3d14328.png)

然后只要退出重启，评论功能又可以正常用了
![image](https://user-images.githubusercontent.com/117956441/227950833-46c1f7ea-4452-4d19-a803-f102d8392a05.png)

**Comment by royc01** [comment]
这个功能不稳定，建议少用
