### ISSUE TITLE
希望日历增加显示未完成的 To Do 的功能

### ISSUE THREAD

**Issue by SkysCrystal** [royc01/notion-theme#172]
Obsidian 上有个 Calender 插件 [如图] 。当天有 Daily Note 的，在日期下面显示一个实心点（这个功能在本主题中已实现）
此外，当天有未完成 To Do 会另外显示一个空心点，完成后此空心点会消失。这个提示未完成 To Do 的功能很实用，希望能增加一下，谢谢！

![image](https://user-images.githubusercontent.com/49473463/228410650-4334625d-5731-4a71-a5f5-c6e61a2dd57a.png)

**Comment by royc01** [comment]
主题不再自带该功能
