### ISSUE TITLE
建议：字体更醒目一些

### ISSUE THREAD

**Issue by remoon1991** [royc01/notion-theme#173]
您好，
小小建议：希望能让字体更醒目一些，尤其是大纲字体，感觉字体可以粗一点点，或者字体颜色深一点点。目前感觉总有一点朦胧感。
毕竟是笔记，有点费眼睛。
谢谢您

**Comment by royc01** [comment]
我这边显示效果觉得还可以，或者通过css改一下字体颜色吧😅
