### ISSUE TITLE
三个问题反馈

### ISSUE THREAD

**Issue by LeeOswald368** [royc01/notion-theme#174]
**小窗口下菜单显示不全**
这是自带主题的
![O707TIymR1](https://user-images.githubusercontent.com/120121713/229338335-742cfa27-4f2a-44a7-9eb6-cef47b93ceb6.png)
这是目前主题的
![HxhxQNJTpv](https://user-images.githubusercontent.com/120121713/229338367-30075d05-f889-480d-9515-03952b899e3a.png)

**窗口标题居中出现bug**

软件窗口拉小的：

![mC8UD3Oyva](https://user-images.githubusercontent.com/120121713/229338836-0632ad54-0e84-48ad-9b60-f30886fa0160.png)

点击一次最大化然后再点向下还原后
![rhZmvYk2BU](https://user-images.githubusercontent.com/120121713/229338859-4cef242c-c3b8-4d8b-98f4-17696e05542e.png)

**日历的提示**
目前日历只能定位于一级目录
![image](https://user-images.githubusercontent.com/120121713/229339034-4e0b0235-26fa-4a02-a32a-8eaa0714a4d8.png)
然而我的笔记本下面结构是
![image](https://user-images.githubusercontent.com/120121713/229339105-55f94832-0019-49ee-8fdd-db634fd85d4b.png)

当前的daily note不适用于我的笔记本结构，我就没有使用，但是每一次启动软件都会弹出相应的红色提示框。
![image](https://user-images.githubusercontent.com/120121713/229339356-4f21ff40-d8f3-4c57-808d-aa11c4311d6b.png)

这个日历的设置是否可以让用户主动去设置，而不在每一次重新启动时产生提示框，当用户点击创建的时候，若没有设置相应笔记本再弹出这个提示框。

**Comment by royc01** [comment]
1、下个版本修复
2、我这边测试没问题，是不是插件影响？
3、日历应该不会提示这个，是不是插件问题？或者把主题删了重新下载

**Comment by LeeOswald368** [comment]
> 1、下个版本修复 2、我这边测试没问题，是不是插件影响？ 3、日历应该不会提示这个，是不是插件问题？或者把主题删了重新下载

感谢提醒。已解决。

**Comment by LeeOswald368** [comment]
> 1、下个版本修复 2、我这边测试没问题，是不是插件影响？ 3、日历应该不会提示这个，是不是插件问题？或者把主题删了重新下载

那是否可以增加日历的笔记本选择，现在只能选择一级笔记本，希望能够向下选择二级或三级以上笔记本
