### ISSUE TITLE
【新功能建议】子弹穿线

### ISSUE THREAD

**Issue by H-a-r-r-o-w** [royc01/notion-theme#175]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/77455480/229402176-b2c4ff8d-b0e3-492c-b956-7f0662dcc240.png">

一个对于无序列表/有序列表的可阅读性加强
图源RemCraft，但RemCraft现在图标无限横向延伸，个人场景下完全无法使用，故而转头Roy家的Savor

**Comment by fenshen000** [comment]
附议，现有的子弹线代码片段在Savor中实现时，会出现线段与列表标点/序号对不齐的情况
![image](https://github.com/royc01/notion-theme/assets/43239563/1de06cac-1e8d-4b6c-8a2d-d07f446a6208)
还有断裂和无法连结的情况
![image](https://github.com/royc01/notion-theme/assets/43239563/1da08605-40ee-4e69-a6a7-e64a1cf05987)

**Comment by royc01** [comment]
v3.6.2

**Comment by HowcanoeWang** [comment]
列表+列表内是标题时，子弹线显示有问题：

![image](https://github.com/royc01/notion-theme/assets/19968935/7b4905f8-f7c9-48d5-89c6-cad9654f07fb)

**Comment by royc01** [comment]
v3.6.5
