### ISSUE TITLE
【Bug反馈】Mac与隐藏顶栏的冲突

### ISSUE THREAD

**Issue by H-a-r-r-o-w** [royc01/notion-theme#176]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/77455480/229403294-b0746893-21a9-4c4e-bbf0-75ff360f9a53.png">
如图所示，如果开启隐藏顶栏会有Mac自带的窗口控制和标签页互相冲突
麻烦Roy佬了！

**Comment by royc01** [comment]
这个暂时没啥好方案。。只能先不隐藏顶栏了，后面再优化

**Comment by H-a-r-r-o-w** [comment]
> 这个暂时没啥好方案。。只能先不隐藏顶栏了，后面再优化

直接右移一部分不能解决吗🤔RemCraft似乎就似乎直接右移的

**Comment by royc01** [comment]
> > 这个暂时没啥好方案。。只能先不隐藏顶栏了，后面再优化
> 
> 直接右移一部分不能解决吗🤔RemCraft似乎就似乎直接右移的

结构不一样，他那个是有顶栏的，只是顶栏与页签合并了，隐藏顶栏就没办法做成这样
