### ISSUE TITLE
[BUG] 页面使用 ALT+B 唤起的提及栏无法点击

### ISSUE THREAD

**Issue by SkysCrystal** [royc01/notion-theme#178]
打开页面，使用快捷键 `Alt + B` 唤起 `反向链接/提及`页面 有如下问题：
![提及按钮无法点击](https://raw.githubusercontent.com/SkysCrystal/ProgramPG/master/asset/202304070945039.gif)

此外，若不打开右侧边栏，`页面提及`的对应按钮会被字数统计遮挡。

**Comment by royc01** [comment]
3.3.3修复
