### ISSUE TITLE
块引用转为看板视图后，会出现块引数次数出现在看板外面

### ISSUE THREAD

**Issue by flowers65** [royc01/notion-theme#18]
你好，将块引用转为看板视图后，会出现块引数次数出现在看板外面，界面很不美观。

**Comment by flowers65** [comment]
![图片1](https://user-images.githubusercontent.com/59280504/182013157-a5230062-1e80-49cc-b11f-b1199e7a864c.jpg)

**Comment by royc01** [comment]
收到，感谢反馈
