### ISSUE TITLE
Uppercase e lowercase

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-theme#180]
I already asked SiYuan's Github for this function, but they deny the request stating that the structure, language and other things are not compatible with it. Therefore, I would like to ask you for a way to add this function to your theme.

To highlight some words, I type in uppercase.

Example: I need rice for lunch / I need RICE for lunch

This is very good when reading.

Is it possible to add an "uppercase" and "lowercase" button somewhere in the program by activating this function?

I saw that in CSS it is possible to add the following field for transformation:

         text-transform: uppercase;
         text-transform: lowercase;

**Comment by royc01** [comment]
Sorry, this function may use inline-elements, probably not consider it.
