### ISSUE TITLE
选中文本的颜色为系统默认

### ISSUE THREAD

**Issue by 70000zhao** [royc01/notion-theme#182]
改变字体颜色的时候看不见效果
![1](https://user-images.githubusercontent.com/91588376/233761151-46e0ca09-5f1a-4c80-b6e0-2cb867abfb32.png)
希望能改进成下图
![2](https://user-images.githubusercontent.com/91588376/233766511-c30899d4-a156-4e53-83f8-2e097e2b3710.png)

**Comment by royc01** [comment]
感谢反馈，下个版本修复
