### ISSUE TITLE
在思源集市找不到了

### ISSUE THREAD

**Issue by PotStove** [royc01/notion-theme#187]
可不要是下架了呀😥

**Comment by royc01** [comment]
![image](https://github.com/royc01/notion-theme/assets/38906705/6717bcd8-bff9-48fa-8825-240cbcb32fb8)

**Comment by PotStove** [comment]
大佬这是哪里截的图？我在自己win客户端找不到，应该是我客户端的问题。

**Comment by royc01** [comment]
更新到最新版本吧
