### ISSUE TITLE
桌面版导出图片不完整

### ISSUE THREAD

**Issue by Jiangshuon** [royc01/notion-theme#192]
浏览器预览页面图片会扩到最大，然后滑动鼠标也没反应
![image](https://github.com/royc01/notion-theme/assets/67137548/1765e316-822a-49eb-93ec-a7efde099ab5)

**Comment by Jiangshuon** [comment]
https://ld246.com/article/1685579838441

**Comment by Ctipsy** [comment]
+1 我也遇到这个问题了，100%复现，导出图片只有一部分区域

**Comment by royc01** [comment]
v3.4.3修复
