### ISSUE TITLE
[v3.4.4] 设置面板在窗口缩窄后左侧栏宽度过大

### ISSUE THREAD

**Issue by littlecoby** [royc01/notion-theme#193]
如图，能否设成和默认主题一样只保留图标的宽度呢，或者保留文字让空白减小。
![image](https://github.com/royc01/notion-theme/assets/27865589/5119a450-aa89-4cdc-9b5d-592de9bfe7c2)

**Comment by royc01** [comment]
了解， 你不说我还不知道有这个功能🤣

**Comment by littlecoby** [comment]
> 了解， 你不说我还不知道有这个功能rofl

哦哦，那坐等下一版

**Comment by royc01** [comment]
v3.4.5修复
