### ISSUE TITLE
导图模式下，一个栏目太窄了，分了好几行

### ISSUE THREAD

**Issue by hhailing** [royc01/notion-theme#195]
感谢大佬的开发，导图模式下，一个栏目太窄了，分了好几行，能否让用户自己通过软回车来设定宽度，谢谢

**Comment by royc01** [comment]
感谢支持，限制宽度的初衷就是防止单个块过长，暂时应该不会取消这个特性。
或者尝试在代码片段里添加这段代码以取消这个限制
.protyle-wysiwyg *[custom-f="dt"] .li div>div[spellcheck]{
max-width: unset!important;}
