### ISSUE TITLE
思源笔记 主题使用反馈：日历组件点击无交互动作

### ISSUE THREAD

**Issue by Ctipsy** [royc01/notion-theme#196]
![Snipaste_2023-06-25_16-34-02](https://github.com/royc01/notion-theme/assets/31062383/9cc97bb7-088f-4c2a-9992-3b30161bd14e)

**Comment by royc01** [comment]
你好，我这边是正常生成日记文档的，或者点击右上角的星期更改笔记本试试看

**Comment by Ctipsy** [comment]
> 你好，我这边是正常生成日记文档的，或者点击右上角的星期更改笔记本试试看

可以了，是因为没有选中笔记本的原因；

不过建议把 “点击日期 可以切换笔记本” 这个功能凸显一下，比如在星期下面配个底色？

**Comment by royc01** [comment]
这个功能应该不优化了，现在有插件支持这个功能，等待成熟后主题日历就会下架
