### ISSUE TITLE
建议适配“替换背景图片插件”

### ISSUE THREAD

**Issue by crafter-z** [royc01/notion-theme#197]
“替换背景图片插件”项目地址https://github.com/HowcanoeWang/siyuan-plugin-background-cover
该插件可以更换思源笔记的背景图片。但是与savor主题之间有轻微的不兼容，对于轻微不兼容的原因在该项目README中有描述。希望作者大大可以据此适配一下！

**Comment by royc01** [comment]
作者单独找过我的，暂时还没时间弄，后续会优化😅
