### ISSUE TITLE
当闪卡在标签页中显示时，显示答案 按键，大部分区域无法点击

### ISSUE THREAD

**Issue by meteor199** [royc01/notion-theme#198]
![image](https://github.com/royc01/notion-theme/assets/21106029/f900dd28-5ccc-48e3-b883-c3547037fedd)

![image](https://github.com/royc01/notion-theme/assets/21106029/5e215101-28d7-4f8d-a819-30aeb957a7a5)

**Comment by royc01** [comment]
下个版本修复，感谢反馈
