### ISSUE TITLE
评论功能无法使用？

### ISSUE THREAD

**Issue by SrSh-notme** [royc01/notion-theme#20]
notion-theme 已结合 lanzhou的评论功能。但是没法用了？

**Comment by royc01** [comment]
你好，我这边使用是正常的

**Comment by TotiUY** [comment]
![Snipaste_2022-08-15_12-40-47](https://user-images.githubusercontent.com/48594308/184577952-21c2cbaf-6c13-4f7d-be4f-02278373843a.png)
这个没有显示评论按钮

**Comment by royc01** [comment]
重新下载一下主题，或者参考指南里“主题”这个章节清除一下缓存

**Comment by TotiUY** [comment]
重装思源笔记了也没用 很奇怪。

**Comment by royc01** [comment]
缓存问题的话，重装软件是没用的，还是清除一下比较快

**Comment by TotiUY** [comment]
请问具体怎么操作，弄了半天没看怎么清楚缓存。

**Comment by royc01** [comment]
ctrl shift i 打开开发者工具，在 `Network` 中勾选 `Disable cache`，在`console`里运行`window.location.reload()`

**Comment by royc01** [comment]
如果不行的话，把主题文件复制一个副本，然后重开思源在外观里面选择那个副本

**Comment by TotiUY** [comment]
还是不行

**Comment by royc01** [comment]
salt主题和notion dark都试一下看能不能行

**Comment by TotiUY** [comment]
![image](https://user-images.githubusercontent.com/48594308/184597606-faaa1115-0d92-4b26-b619-04b3fd2e5819.png)
都不行，是不是因为上图这个原因？

**Comment by royc01** [comment]
上图正常的
![1](https://user-images.githubusercontent.com/38906705/184597799-38b64552-796b-4ebe-85c7-38b6fca18a76.jpg)
我这边正常使用，或者你重启电脑再看看，不行就真的没办法

**Comment by TotiUY** [comment]
没用。很奇怪...  这个浮动工具条的样式也跟你的不一样。修改主题后工具条样式没变。

**Comment by royc01** [comment]
样式应该一样的，只是图标有点差别，其他有评论功能的主题能用吗，这个功能几个月没改过了，应该不会变化的

**Comment by TotiUY** [comment]
估计是浮动工具栏按钮被遮挡 或者 没生效。

**Comment by royc01** [comment]
这就不太清楚了，我这边一直正常使用。。。

**Comment by TotiUY** [comment]
mini-vlook 浮动工具栏能显示评论图标 
![image](https://user-images.githubusercontent.com/48594308/184797254-bda0fa9c-d68b-4350-8618-7f773d6320a0.png)
但是使用有问题
![image](https://user-images.githubusercontent.com/48594308/184797357-d57459fa-d588-46b9-9ba8-c1cf176c0020.png)

**Comment by SrSh-notme** [comment]
找到问题解决方案了。关闭使用系统原生emoji。一切正常。
![image](https://user-images.githubusercontent.com/48594308/184809667-14c8cd72-62e0-445e-a262-41892401f221.png)
![image](https://user-images.githubusercontent.com/48594308/184809694-65d1b6bf-10ed-4fac-ac15-49d2056b35a9.png)
![image](https://user-images.githubusercontent.com/48594308/184809871-387f52ba-a620-4907-bd62-def9b9e91b10.png)

**Comment by royc01** [comment]
啊。。原来是这样吗，学习了
