### ISSUE TITLE
字体颜色的问题

### ISSUE THREAD

**Issue by whossun** [royc01/notion-theme#202]
不管是亮色还是暗黑模式下字体颜色都是白色的，那么 在亮色模式下提示词基本看不见
![image](https://github.com/royc01/notion-theme/assets/6230250/f88e058f-634f-40e3-9959-0a4d72f31d3e)
![image](https://github.com/royc01/notion-theme/assets/6230250/ce3b89ad-72d8-4b37-964f-92cf7dac497d)
***
![image](https://github.com/royc01/notion-theme/assets/6230250/201358e9-c57f-44b9-a6ca-b21916a95e3c)
![image](https://github.com/royc01/notion-theme/assets/6230250/bb49fbc6-6de0-4c16-b3ea-23e90e6bf2b2)
***
这个是我软件的问题还是配色的问题？

**Comment by royc01** [comment]
软件和主题都更新到最新版本，然后重开思源就可以
