### ISSUE TITLE
ctrl+p 搜索內容中有空格時，搜索結果會缺少空格

### ISSUE THREAD

**Issue by Louie901119** [royc01/notion-theme#204]
用 ctrl+p 搜索時，如果搜索內容中有空格，搜索結果會缺少空格。

例如有一個文檔如下：
![image](https://github.com/royc01/notion-theme/assets/88768177/b42e347d-63e5-404b-ab66-514714dec719)

用 ctrl+p 搜索 test file 時，搜索結果會缺少空格，如下圖：
![image](https://github.com/royc01/notion-theme/assets/88768177/633a40a0-742f-40c0-b63e-63754d12be63)

**Comment by royc01** [comment]
感谢反馈，下个版本修复

**Comment by Louie997** [comment]
感謝上一次的修復，
但是在最新版本中好像又出現這個問題了。
