### ISSUE TITLE
跪求大佬改下5级标题的配色

### ISSUE THREAD

**Issue by Jiangshuon** [royc01/notion-theme#205]
土黄色和背景区分度太低了，看着很费劲，而且不太好看

![image](https://github.com/royc01/notion-theme/assets/67137548/23b63346-9ea8-4429-8928-4d180f660f11)
<img width="467" alt="image_61" src="https://github.com/royc01/notion-theme/assets/67137548/6cd608bf-2da3-4a81-bf48-edea3f3628d8">

**Comment by royc01** [comment]
下个版本优化
