### ISSUE TITLE
能否考虑把"/"功能菜单，做成4列的，谢谢

### ISSUE THREAD

**Issue by yakoye** [royc01/notion-theme#206]
![image](https://github.com/royc01/notion-theme/assets/16289151/34a4a487-79ab-4fc5-b8b7-c6b9ce518c48)

一直在用你的主题，能否把做成4列或多列的，一眼能看到全部，不用翻页。谢谢

**Comment by royc01** [comment]
你好，新版v3.5.0已经修复了这个问题，请更新一下主题
