### ISSUE TITLE
新版主题中样式细节的一些问题

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#208]
思源版本：v2.9.9
主题版本：v3.5.3
操作系统：win10

## 样式细节的一些问题

1. 把右侧边栏中的所有面板移动到其他区域后，状态栏与右下角角落之间存在空隙。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/56f13790-e5a0-48fe-9b16-3ef552aa62e8)
2. 把右侧边栏中的所有面板移动到其他区域后，右侧边栏中的切换配色、隐藏顶栏等功能就无法显示和使用了。
    要不要考虑把主题多出来的这些按钮合成一个按钮放在顶栏？按下打开一个菜单那种，参考代码块的设置菜单那样每个选项都可以开关，这样看起来就不会像旧版那样特别多按钮。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/e526707d-eda6-4849-80d7-96d76fed7285)
3. 在设置中打开了隐藏状态栏后，底部的边缘间距的问题。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/dd1991a5-5cb2-4adf-8cbc-c0980bab2da1)
4. 使用新窗口打开笔记的窗口样式问题。
    顶部边缘间距的问题。
    新建文档+与关闭页签 x 没有在同一水平线上，与此相对的原窗口打开时就没有该问题。
    钉住、最小化、最大化的位置问题，最大化与关闭之间的间距比其他按钮之间的间距更大的问题。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/9de44010-17ff-4275-bc42-9694cab1466d)
5. 打开设置后“退出只读”样式问题。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/c7e67099-0189-41f3-b190-4817ec579406)
6. 开关“只读模式”后，影响标题居中位置，调整窗口大小后标题位置跳动的问题。
    看起来是只读模式按钮宽度变化所导致的。
    ![整窗口大小后标题位置跳动](https://github.com/royc01/notion-theme/assets/86591721/be9e245f-49c8-4fa9-af2c-408a8e5937e3)
7. 滑动条样式问题。
    圆内缺一角，和 0 和 100 的情况下圆外缺一角的问题。
    感觉可以做成白色实心的圆。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/abc334ef-5d4a-4188-9a2d-275f4a0bb15b)![image](https://github.com/royc01/notion-theme/assets/86591721/13eb2e90-c519-4492-9a41-96c7095dd4ce)![image](https://github.com/royc01/notion-theme/assets/86591721/1d77f28e-24cb-458a-b8ec-e01e5b253e5a)
8. 引述块icon的位置偏下的问题。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/0363c90e-18ff-4e15-afe6-f6c78b108e12)
9. 列表转换为表格视图后奇怪的圆角问题。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/4cf24241-1dc3-44bf-93f9-2990d7ba7d96)
10. 表格使用页面宽度后右上角缺口的问题。
     正常情况下不论是表格内容太多占满了宽度还是手动调整宽度到占满都没有这个现象。
     ![image](https://github.com/royc01/notion-theme/assets/86591721/a66e193e-474e-49e6-8ac8-f13424051bce)

## 下侧边栏的问题

1. 如果有任何面板被移动到下侧右方，则会和状态栏重叠并被挡住。
    悬浮状态栏的情况下，感觉这部分处理成下侧边栏在状态栏下面可能是最好的了。
    如果按照原生的样式来就会变成不透明下侧边栏在上，状态栏在下，就很奇怪。
    不过反正实际使用中我完全不用下侧边栏就是了 🤔
    如图，挡住了收集箱。
    ![image](https://github.com/royc01/notion-theme/assets/86591721/3dd6597f-5bfb-4cef-b6de-7c6ce4eebf4d)
2. 下侧边栏的浮动面板样式问题，有考虑做适配吗？
    ![image](https://github.com/royc01/notion-theme/assets/86591721/e11e5e33-8c40-409d-a5c4-4a27fb61c688)

---

## UI上细节的适配还是很费功夫的，感谢作者提供的主题，辛苦了❤

**Comment by royc01** [comment]
感谢反馈与支持，后续一一优化。

**Comment by royc01** [comment]
v3.5.4修复
