### ISSUE TITLE
salt配色隐藏顶栏后左右上角颜色问题

### ISSUE THREAD

**Issue by XinLi0111** [royc01/notion-theme#209]
![image](https://github.com/royc01/notion-theme/assets/31495943/433b8215-f483-43fd-9a58-ca5f54fae187)

**Comment by royc01** [comment]
新版顶栏还没适配替换背景插件，后续优化

**Comment by royc01** [comment]
新版插件修复

**Comment by XinLi0111** [comment]
slat配色隐藏顶栏后似乎还是有些问题，或者是需要怎么处置一下吗？我重新刷新过思源，切换过主题，还是这样。默认的亮色主题是正常的。
![image](https://github.com/royc01/notion-theme/assets/31495943/4eb37e76-e0e1-46d8-bcec-0b6a83124d4d)
![image](https://github.com/royc01/notion-theme/assets/31495943/5c47895f-a4a7-4fa6-b7cf-b4b5f3df1484)

**Comment by royc01** [comment]
bug 下个版本修复
