### ISSUE TITLE
在主题样式中发现的一些配色问题

### ISSUE THREAD

**Issue by shawnyuan-cn** [royc01/notion-theme#211]
1. **”链接“转上下标时会丢失样式**
![image](https://github.com/royc01/notion-theme/assets/105029931/45b4e608-dee2-4888-995c-90caa8556b7e)

2. **“备注”样式**
![image](https://github.com/royc01/notion-theme/assets/105029931/8688dbab-9e93-4646-bac1-d5e04a0d254b)
以下是仅我的一些看法：
- 备注功能**不需要类似标记的背景色高亮强调**效果，而是作为markdown脚注功能的一个替代，过分突出有些喧宾夺主的意思。
- 蓝色的基本**配色有些突兀**，在主题色中甚至比标记的浅黄色明显
- 以下是使用现链接样式添加的注释(伪)，感觉效果更接近我的理想样式
![image](https://github.com/royc01/notion-theme/assets/105029931/01596906-23d7-4593-b90d-12c2d2ecf855)
![image](https://github.com/royc01/notion-theme/assets/105029931/e92d175a-31ba-43a6-8624-ba016cd32c86)

**Comment by royc01** [comment]
这样做的话备注样式跟链接样式太接近，不好区分

**Comment by royc01** [comment]
链接样式在v3.5.4修复
