### ISSUE TITLE
【bug】点击有序列表中子列表的序号时，hover样式错误

### ISSUE THREAD

**Issue by HarryHuaa** [royc01/notion-theme#216]
![image](https://github.com/royc01/notion-theme/assets/11732858/4dc5b142-1109-4bc5-8060-461d92cfea45)
![image](https://github.com/royc01/notion-theme/assets/11732858/f60c48d9-e0fd-4f04-8f6e-686b4590f2ec)
如图所示，子列表中的序号均显示为了1，正确显示应该是a或i

**Comment by royc01** [comment]
已经修复了，下个版本更新，感谢反馈
