### ISSUE TITLE
大佬，移动端的最近文档和搜索页面的图标和文字没有对齐

### ISSUE THREAD

**Issue by Jiangshuon** [royc01/notion-theme#217]
![94ab0ea17bcbf3c400365fb36f6aa70](https://github.com/royc01/notion-theme/assets/67137548/98944ae5-c2a2-4eaa-a35b-85e31b95c69e)

**Comment by royc01** [comment]
好的，我后面修复一下

**Comment by royc01** [comment]
v3.5.8
