### ISSUE TITLE
列表转成表格后无法显示完全

### ISSUE THREAD

**Issue by Allxy5** [royc01/notion-theme#218]
把列表转成表格的时候，如果列表子级太多，表格后面的部分超出显示框被挡住，也没法拖动查看被档的内容，后面的内容都看不见。
![image-pdwfP9J](https://github.com/royc01/notion-theme/assets/112512003/6c07400d-a61c-44e5-b8f2-96e0993bd536)
![image-He7w579](https://github.com/royc01/notion-theme/assets/112512003/ac1a369c-0505-4d7e-8fb1-02655295268f)

**Comment by royc01** [comment]
你好，论坛上已经回复了哈

**Comment by royc01** [comment]
v3.5.7
