### ISSUE TITLE
块图标乱串

### ISSUE THREAD

**Issue by EberhardLin** [royc01/notion-theme#22]
![「思源笔记」主题Notion-Theme块图标乱串事件](https://user-images.githubusercontent.com/98400319/190555788-74ed7fad-2318-42d7-b038-e426b418e48b.gif)
具体见动图，块图标在段落块与一级无序列表项之间，会使块图标（段落块）串到右边去。
不影响实际使用，仅观感不好。

**Comment by royc01** [comment]
我这边重现不了，具体是怎么做的？

**Comment by EberhardLin** [comment]
经过仔细的研究，已发现重现的触发机制，但需要满足多个条件，有些条件不具备普遍性，个人认为似乎解决意义不大，你看看有没有必要吧，我个人觉得似乎没必要。

**Comment by EberhardLin** [comment]
1. 将程序窗口分屏至右侧（通过「Win」＋「→」或「←」组合键/直接将窗口拖动顶到最左侧或者最右侧）
2. 需要大纲栏在右侧显示，关闭文档树，右侧显示大纲栏，如图所示：
![image](https://user-images.githubusercontent.com/98400319/190585375-e5279eb3-53ec-43c2-a8d4-f1d1309c3c8f.png)
3. 在这个状态下，找一篇文档长度足够加载「动态加载进度条」的文档。
4. 并且出现该现象必须是段落块在上、列表块在下，两者并排，并且字数必须够多，长度必须都是长到换行。
5. 之后就可以像动图一样重现该现象。

**Comment by EberhardLin** [comment]
换了默认主题测试，发现默认主题也会，不好意思没有多加测试，应该不是主题问题，非常抱歉。

**Comment by royc01** [comment]
没事，感谢反馈
