### ISSUE TITLE
列表转表格后，不是竖着排了

### ISSUE THREAD

**Issue by Allxy5** [royc01/notion-theme#220]
![image](https://github.com/royc01/notion-theme/assets/112512003/9d1dfe51-9c88-4a0d-99ee-9f8167bf6a8c)
![image](https://github.com/royc01/notion-theme/assets/112512003/fd90a8da-2e5b-45d7-8fc7-51feb22b67bf)

之前转表格后，A，B，C在同一列，现在变成横着排了

**Comment by royc01** [comment]
收到
