### ISSUE TITLE
PDF导出的样式

### ISSUE THREAD

**Issue by jl0476** [royc01/notion-theme#221]
您好，
Savor主题PDF导出时，自带一个底色。现在代码块颜色和底色颜色很相近，没法进行区分。希望能够修改下PDF导出的样式。

![image](https://github.com/royc01/notion-theme/assets/5226690/a8b32ad2-e775-4589-9841-0890d2ea05b3)

默认官方主题的效果：
![image](https://github.com/royc01/notion-theme/assets/5226690/9ed5972c-be6f-4610-8df1-7ca63047a5bd)

**Comment by royc01** [comment]
v3.5.10
