### ISSUE TITLE
大佬，移动端的默认文档图标能修改一下吗？看着违和

### ISSUE THREAD

**Issue by Jiangshuon** [royc01/notion-theme#224]
![cd46ad07bc9035f504b27f32d532541](https://github.com/royc01/notion-theme/assets/67137548/01e11dd0-3bf9-4bbb-be84-a09b67362856)
![2710c6e4b854d6456d4a6a7c3147ca1](https://github.com/royc01/notion-theme/assets/67137548/2264e9dd-942c-45d9-a361-e0d5b3b97f5d)
第二张截图中，左边那种看着就很舒服。
这是由主题控制的吗？

**Comment by royc01** [comment]
v3.6.2
