### ISSUE TITLE
暗黑模式下PDF高亮颜色看不清

### ISSUE THREAD

**Issue by LoneFireBlossom** [royc01/notion-theme#226]
好几个颜色不细看很难认出来😂我想是因为本主题用的高亮颜色都是淡色
我觉得可以把下面那个框的颜色调一下让颜色对比更明显

<img width="148" alt="image" src="https://github.com/royc01/notion-theme/assets/50087596/451ea6c2-6430-46d4-8ab7-e412f4483845">

感谢你开发的主题

**Comment by TCOTC** [comment]
亮度可以高一点？

**Comment by TCOTC** [comment]
@LoneFireBlossom 解决了？

**Comment by LoneFireBlossom** [comment]
开发者不需要我这个建议吧，而且这个是不是CSS可以自己调整，不需要非得让主题去改

**Comment by royc01** [comment]
一般不关闭的是暂时没时间弄，或者需要时间思考
