### ISSUE TITLE
引述块类「Callout」样式问题

### ISSUE THREAD

**Issue by fenshen000** [royc01/notion-theme#229]
当引述块处于某个列表的子级后，在「视角选择」选择类似于「Callout」样式，会出现如图所示的问题：
鼠标光标处于该引述块或其父级列表内任意位置，引述块前面的图标会被动拉长
![2](https://github.com/royc01/notion-theme/assets/43239563/cc85f5ad-6bef-457b-8fd4-afd4e04fceb3)
假如该引述块不是列表块的子级时，图标就是正常的
感觉应该是个bug，大佬有空看一下哈
谢谢~

**Comment by royc01** [comment]
应该跟代码片段冲突，先关闭试试

**Comment by fenshen000** [comment]
还真是，和列表块`子弹线`的代码片段冲突了...
