### ISSUE TITLE
属性视图适配

### ISSUE THREAD

**Issue by jl0476** [royc01/notion-theme#230]
![image](https://github.com/royc01/notion-theme/assets/5226690/9510fb8a-703c-4d7a-b166-5081eb735e50)
![image](https://github.com/royc01/notion-theme/assets/5226690/362697d6-b282-4153-ba96-f23ffc43c9e1)
![image](https://github.com/royc01/notion-theme/assets/5226690/77d26628-0db8-46fb-a493-5a75de47eb01)

属性视图是不是还未完全适配。
现在属性视图编辑时还有一定卡顿，另外编辑的过程中底层文字还叠加在一起。
烦请适配，辛苦！

**Comment by royc01** [comment]
卡顿应该跟主题没关系，样式适配后面会做，最近比较忙呢，感谢反馈

**Comment by royc01** [comment]
v3.6.2
