### ISSUE TITLE
属性面板圆角丢失、闪卡管理圆角丢失、子弹穿线样式错误

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#236]
1. 任何块-右键-属性，圆角丢失问题
![image](https://github.com/royc01/notion-theme/assets/86591721/b4a2fefe-072c-4539-b0c5-79885eb86977)

2. SIYUAN主菜单-闪卡-管理，圆角丢失问题
![image](https://github.com/royc01/notion-theme/assets/86591721/2876fa60-bf7f-4cc0-9f0a-4b8c8fd43f59)

3. 有序列表或无序列表-右键-视图-进度条任务，子弹穿线样式错误问题
进度条任务功能不适用于有序列表和无序列表，建议在这两种列表的右键里不显示这个。
![image](https://github.com/royc01/notion-theme/assets/86591721/17c7baae-9301-4fab-ae86-4f35a937d885)
---
思源版本 v2.10.10
主题版本 v3.6.4

**Comment by royc01** [comment]
1、2下个版本修复 3暂时不弄了
