### ISSUE TITLE
标题块折叠状态下，超级块的显示问题

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#237]
使用时遇到这样的bug:
只要标题块下面有超级块，折叠该标题块后，关闭文档再打开，折叠的标题块下面就会出现和超级块数量相等的小方块:(
![image](https://github.com/royc01/notion-theme/assets/43239563/676d2f1d-5cd3-403c-a815-a6e1b13716a6)
![1](https://github.com/royc01/notion-theme/assets/43239563/e536c3c5-629c-4b56-81ea-04388612f831)

原本认为是思源加载的问题，不过在默认主题下测试是没有问题的，感觉应该是savor主题在这里有点小bug了

**Comment by royc01** [comment]
你好，经测试，默认主题也会出现这个问题，只是没有添加背景色，但也是有占位。

**Comment by QMike0** [comment]
这样啊，那我去官方那边提个issue

**Comment by QMike0** [comment]
欸，在那边看到大佬你提过了，那没事了哈哈
