### ISSUE TITLE
能否考虑增加类似浏览器的标签栏模式，以能够实现文档的二维快速选择

### ISSUE THREAD

**Issue by pisceswb** [royc01/notion-theme#239]
写未主题是最受用户青睐的主题，希望作者长期维护下去。
关于文档树方面，请问作者能否开发一个类似浏览器的标签栏模式，以能够实现文档的二维的横向和纵向都能选择的文档树模式。横向列出所有笔记本（横向显示内容更多），点击打开后，能够显示该笔记本中的所有文档（包含子文档）。这将会比当前文档树模式仅能一维纵向选择文档方便的多。希望作者能够采纳建议，谢谢！
![image](https://github.com/royc01/notion-theme/assets/104658457/1c12a287-6ae7-43b0-81ed-a5408bfe9f4c)

**Comment by royc01** [comment]
研究了一波，冲突较大，而且官方取消了顶部停靠栏，不好实现，暂时不做了，感谢反馈
