### ISSUE TITLE
为啥我的行内代码不是红色

### ISSUE THREAD

**Issue by zzw6776** [royc01/notion-theme#24]
这是主题的介绍页面
![image](https://user-images.githubusercontent.com/14048998/192132748-a94f4f33-1afd-4851-972c-8398e08cd72a.png)
这是我应用主体之后
![image](https://user-images.githubusercontent.com/14048998/192132752-204c65d3-e4c9-4e7f-a73d-ab65eabdc9cb.png)
如题

**Comment by royc01** [comment]
新版还没适配，下个版本更新
