### ISSUE TITLE
salt配色下状态栏位置问题，题头图按钮问题

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#241]
salt配色下状态栏位置
![image](https://github.com/royc01/notion-theme/assets/86591721/063ee89c-9490-4d3a-928a-2fef043c37ad)
---
题头图按钮
![image](https://github.com/royc01/notion-theme/assets/86591721/a0eac911-ca3d-4575-8fd8-4516b536e599)
---

**Comment by royc01** [comment]
正在漫长的重构中

**Comment by CKlimeths** [comment]
辛苦了！
话说思源官方的更新改动还是很频繁的，导致部分样式也频繁失效，一直这么频繁的维护也不是办法🤔。

**Comment by royc01** [comment]
没办法啊。。所以尽量做得相对稳定点好了

**Comment by royc01** [comment]
v3.6.7
