### ISSUE TITLE
开启底栏后，反链提及点击被底栏悬浮打断

### ISSUE THREAD

**Issue by XinLi0111** [royc01/notion-theme#244]
![image](https://github.com/royc01/notion-theme/assets/31495943/801d46da-50ea-489e-bacd-ce07712c1cae)

**Comment by royc01** [comment]
v3.6.7

**Comment by XinLi0111** [comment]
https://github.com/siyuan-note/siyuan/issues/9750

**Comment by XinLi0111** [comment]
左侧的已关闭文档和右下角的帮助文档按钮等，依旧会被底栏悬浮窗遮挡

**Comment by royc01** [comment]
> 左侧的已关闭文档和右下角的帮助文档按钮等，依旧会被底栏悬浮窗遮挡

给官方issue回复反馈？

**Comment by XinLi0111** [comment]
这几个按钮都不能点击了，鼠标一过去就弹出底栏浮窗
![image](https://github.com/royc01/notion-theme/assets/31495943/d044ab5f-3266-4ae7-9e96-df71cf11b3b2)

**Comment by royc01** [comment]
我知道，我是说默认主题下，关闭底部工具栏好像依然被遮挡。

**Comment by XinLi0111** [comment]
嗯嗯，刚才没看明白，已经在官方 issue 下回复了。感谢！！

**Comment by XinLi0111** [comment]
官方已更新，辛苦大佬在有空的时候修复

**Comment by XinLi0111** [comment]
3.7.6 版本，还是有点问题。帮助又无法点击到了。底栏悬浮还不是从底栏顶部开始，而是底栏上方的空白区域就开始出发悬浮窗了
![PixPin_2023-12-06_12-44-54](https://github.com/royc01/notion-theme/assets/31495943/ff8ffee8-2a05-413c-96b8-fb7860251b87)

**Comment by royc01** [comment]
😞下个版本应该就好了
