### ISSUE TITLE
你好，Savor搜索页bug：保存的查询条件 遮挡 搜索历史

### ISSUE THREAD

**Issue by zzz51522** [royc01/notion-theme#245]
这是搜索框处于弹窗状态时，搜索历史 被 查询条件 遮挡
![image](https://github.com/royc01/notion-theme/assets/145221733/f4fecb3d-9c8e-4699-9953-cc43054b99d2)

这是搜索框处于页签状态时，搜索历史 被 查询条件 遮挡
![image](https://github.com/royc01/notion-theme/assets/145221733/2b429636-4f63-4e6a-9cf4-143254e79c7e)

如有时间，辛苦修改，感谢

**Comment by royc01** [comment]
感谢反馈 v3.6.9修复
