### ISSUE TITLE
关于新版Savor优化的一点想法

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#247]
佬，为啥`行级代码`不默认为红色了呀，感觉之前的要醒目和好看的多555。可不可以改一下，或者提供一下之前这部分的代码片段，我自己加进去。谢谢佬~

另外light模式下，`设置-外观-代码片段`采用淡黄色背景，而代码输入框是白色背景，且没有明显边框，个人感觉看起来有点怪怪的，而且代码输入框的边界不那么清晰
>现在light模式许多界面采用的淡黄色背景不太喜欢哈哈哈，之前好像没有明显感觉到light模式这么多淡黄色的存在

![image](https://github.com/royc01/notion-theme/assets/43239563/171b23b8-40b8-451c-8149-4220eb05e696)
其他的细节改动还在探索中~

**Comment by royc01** [comment]
你好，行级代码的样式应该没改过，还是红的。代码片段的底色是比之前面板底色更浅一点，更清爽一点

**Comment by QMike0** [comment]
谢谢佬回复~

重新看了下，原来是我添加的代码片段有误，导致的`行级代码`颜色回到默认主题的样式，更改后就好了

淡黄色背景+白色输入框 感觉还是有点奇怪哈哈，我再适应适应

再次感谢佬的主题

**Comment by royc01** [comment]
好的，感谢反馈

**Comment by QMike0** [comment]
佬，想顺便问下，Savor主题可以支持多行页签吗
这是链滴里面抄到的多行页签CSS代码片段
```
.layout-tab-bar.fn__flex, ul.fn__flex.layout-tab-bar {
    flex-wrap: wrap;
}
.fn__flex-column.fn__flex.fn__flex-1 .fn__flex:has(.fn__flex.layout-tab-bar){
	max-height: 100%;
}
```
但加到Savor里面后，Savor好像把页签所在行的高度固定了，多行时无法正常显示
![image](https://github.com/royc01/notion-theme/assets/43239563/3cabb6c1-80dd-4641-b8a8-15099df6d3f7)

默认主题下是可以正常显示出来的：
![image](https://github.com/royc01/notion-theme/assets/43239563/e310f5ce-3444-4d1c-87c3-5e69ac4112a9)

有没有办法修改让多行页签正常显示出来呢

**Comment by royc01** [comment]
`.layout-tab-bar{height: unset;}`取消高度就可以了，但是Savor已经有垂直标签特性，我觉得这样更加优雅

**Comment by QMike0** [comment]
欧克

垂直页签会更好看些，不过会占用一些屏幕纵向的空间，在电脑屏幕较小时就会导致编辑器界面显得很窄。
所以打算用多行页签多提供个页签的展示选项
