### ISSUE TITLE
屏幕上出現幾個紅點

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-theme#25]
屏幕上出現幾個紅點
![siyuan](https://user-images.githubusercontent.com/90691302/192152081-83ebd4d2-c0a8-4ea6-bbf9-1a9956e83754.gif)

**Comment by royc01** [comment]
感谢反馈，下个版本修复

**Comment by SrSh-notme** [comment]
期待修复，同时期待siyuan-comment的整合更新。已经离不开这个主题了。

**Comment by SrSh-notme** [comment]
同时希望大神能够优化下siyuan-comment的标注样式 有个高亮之类的 现在只是加粗 不太明显

**Comment by royc01** [comment]
> 同时希望大神能够优化下siyuan-comment的标注样式 有个高亮之类的 现在只是加粗 不太明显

嗯，近期会更新的

**Comment by taozina0587** [comment]
朋友，问题出在“h-reminder.css”文件中。 如果我删除文件，我报告的错误就会消失。
