### ISSUE TITLE
数据库输入框重影

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#250]
思源v2.11.0，Savor v3.7.3

在向数据库输入内容时，会出现原文本与正在输入的文本重影的情况
以`文本框`为例：
![image](https://github.com/royc01/notion-theme/assets/43239563/6c2ad501-1d09-40be-b9bd-c2e197cb1cc4)
以`数字框`为例：
![image](https://github.com/royc01/notion-theme/assets/43239563/5651bbd4-b21a-4f1c-be0c-8ea397529942)

**Comment by royc01** [comment]
v3.7.4修复
