### ISSUE TITLE
Salt配色的“切换配色”按钮颜色没有显示

### ISSUE THREAD

**Issue by edward-kyle** [royc01/notion-theme#254]
![image](https://github.com/royc01/notion-theme/assets/78415230/fdedd7fa-5030-43ba-be15-59ecc7ade9d7)
salt配色

![image](https://github.com/royc01/notion-theme/assets/78415230/5b2cdf31-da52-411f-82a4-1a8c8dae60ac)
sugar配色

**Comment by royc01** [comment]
v3.7.8
