### ISSUE TITLE
样式上的小建议：标签位置，标题提示符位置

### ISSUE THREAD

**Issue by littlecoby** [royc01/notion-theme#257]
试着提两个样式上的小建议。

1. 文档标签的位置：建议放在左侧，和默认主题类似，这样可以离“添加标签”的按钮近一些，删除时光标不需要移动太长的距离
![tagposition](https://github.com/royc01/notion-theme/assets/27865589/f4c09b12-462e-41e3-a416-85e9d0baa447)

2. 标题提示符的位置：建议放在文字左侧，这样不同层级的辨识度更高一些，后面附上了css
![1702195531805](https://github.com/royc01/notion-theme/assets/27865589/cfef0a01-9c8a-4ad8-a1b9-6ee08ee1ab67)
[h-reminder.zip](https://github.com/royc01/notion-theme/files/13627003/h-reminder.zip)

**Comment by royc01** [comment]
感谢反馈
1. 添加删除标签的操作不是太高频，所以做到右侧，减少视觉区域的信息量
2. 同样，标题层级提示只是辅助辨识，辨识度不适宜太高，会造成压力，偏离极简的原意

**Comment by littlecoby** [comment]
> 感谢反馈
> 
> 1. 添加删除标签的操作不是太高频，所以做到右侧，减少视觉区域的信息量
> 2. 同样，标题层级提示只是辅助辨识，辨识度不适宜太高，会造成压力，偏离极简的原意

感谢回复，有些样式是比较看各人的使用习惯吧，我操作标签还挺频繁的。

问一下，h-reminder.css能通过设置-代码片段关闭吗？

**Comment by royc01** [comment]
可以使用display:none 去屏蔽伪元素，不过最快的办法肯定是直接删了那个css

**Comment by littlecoby** [comment]
> 可以使用display:none 去屏蔽伪元素，不过最快的办法肯定是直接删了那个css

okok
