### ISSUE TITLE
关系图更多设置中的滚动条丢失，导致元素显示不全

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#258]
默认主题这里有滚动条，savor里没有了。
不仅是侧边栏的关系图和全局关系图，通过编辑区右上角菜单打开的也有相同的问题。

![image](https://github.com/royc01/notion-theme/assets/86591721/dc7d6f7e-61e0-4e1a-9344-547ea6ccc5a8)

**Comment by royc01** [comment]
v3.8.1
