### ISSUE TITLE
callout样式出现问题

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#259]
savor主题已更新至最新版

callout样式在savor主题中显示为这样：
![image](https://github.com/royc01/notion-theme/assets/43239563/ed97af8c-435b-434a-89a1-3b0ad6f0e3fc)

默认主题和其他主题中显示正常：
![image](https://github.com/royc01/notion-theme/assets/43239563/2f9e5762-4013-4dcd-a29a-fd7dab0f0168)

**Comment by royc01** [comment]
你好，主题内置有这功能，跟插件有冲突，关闭插件即可。

**Comment by QMike0** [comment]
确实是这个导致的，谢谢佬~
