### ISSUE TITLE
Callout菜单中“视图选择”丢失

### ISSUE THREAD

**Issue by TracyIverson** [royc01/notion-theme#260]
我在左右分屏，左边是正常笔记，右边是PDF的情况下，菜单中无法显示“视图选择”项。我关闭了所有的插件，删除了所有代码片段也是如此。
![1702548945556](https://github.com/royc01/notion-theme/assets/27794098/b69ee44c-ea01-4496-9565-0b38e0846bde)

**Comment by royc01** [comment]
暂时没有好办法  先顶顶

**Comment by royc01** [comment]
v3.8.9
