### ISSUE TITLE
docker版本显示异常

### ISSUE THREAD

**Issue by jl0476** [royc01/notion-theme#262]
![image](https://github.com/royc01/notion-theme/assets/5226690/b244e85f-f3fc-4191-a16b-49e33ebfba01)

docker版本安装最新的3.8.1之后，右侧无法调整风格
清理浏览器缓存后也无效。

**Comment by royc01** [comment]
我这边显示正常，删了主题重新下载看看

**Comment by jl0476** [comment]
> 我这边显示正常，删了主题重新下载看看

删了n次了，都没啥效果。
我其他的容器也正常，就这一个，怎么也调不好。

**Comment by royc01** [comment]
用其他浏览器呢？

**Comment by jl0476** [comment]
> 用其他浏览器呢？

用edge正常，奇怪了，这个chrome就是不行。

**Comment by royc01** [comment]
那就不清楚啥原因了。。能用就行，先关闭了
