### ISSUE TITLE
侧栏面板覆盖设置、数据库块添加按钮

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#264]
未钉住的侧栏面板会覆盖到设置界面上方
![image](https://github.com/royc01/notion-theme/assets/86591721/a9049ed2-5556-46c1-af03-8a2ef53160ac)

数据库块添加按钮，鼠标放在上面时的样式问题
![image](https://github.com/royc01/notion-theme/assets/86591721/10a517b6-f8ce-47cb-b010-64ad9710d7bc)

**Comment by royc01** [comment]
覆盖到设置界面上方是官方的机制，这个不改了

**Comment by royc01** [comment]
2. v3.8.4修复

**Comment by CKlimeths** [comment]
> 覆盖到设置界面上方是官方的机制，这个不改了
好的，这个问题我去给官方论坛反馈了。
