### ISSUE TITLE
垂直页签与数据库冲突

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#265]
未开启垂直页签：
![image](https://github.com/royc01/notion-theme/assets/78434827/9a6e9f3c-2445-4e66-b2a2-954e93bde853)

开启垂直页签：
![image](https://github.com/royc01/notion-theme/assets/78434827/cd60f6ed-9a08-423a-ac47-ff73181fe61b)

**Comment by royc01** [comment]
v3.8.4修复
