### ISSUE TITLE
V3.8.6底栏样式变高了

### ISSUE THREAD

**Issue by winter60** [royc01/notion-theme#266]
![image](https://github.com/royc01/notion-theme/assets/23653326/d5967210-5c72-4bdc-8dbf-ada0f0cbb460)
之前的版本正常

**Comment by royc01** [comment]
为了适应悬浮底部面板触发区域，3.8.6改了不合并的形式，3.8.7改回来，但是不钉住的时候依然为高底栏，感谢反馈。
