### ISSUE TITLE
思源 2.11.4版本，主题适配有异常

### ISSUE THREAD

**Issue by Ctipsy** [royc01/notion-theme#267]
![image](https://github.com/royc01/notion-theme/assets/31062383/8283fd53-89a3-4090-85e8-200b8471ec86)
![image](https://github.com/royc01/notion-theme/assets/31062383/58ba0b0b-fd91-472c-a888-e506d6ed4072)

**Comment by Ctipsy** [comment]
设置页的排版是错位的，混乱的

**Comment by royc01** [comment]
下载新版本重启一下就可以
