### ISSUE TITLE
多彩标题的支持

### ISSUE THREAD

**Issue by hackerhui** [royc01/notion-theme#270]
希望不同的标题采用不同的颜色，这样醒目

**Comment by royc01** [comment]
使用sugar配色可以达到这样的效果

**Comment by QuQu** [comment]
请问如何使用sugar配色呢？

**Comment by royc01** [comment]
> 请问如何使用sugar配色呢？

右上角可以切换配色

**Comment by QuQu** [comment]
![image](https://github.com/royc01/notion-theme/assets/961425/f9709881-e0e6-4f6e-a8fe-bb4afcf4883f)

非常感谢。非常好用。
