### ISSUE TITLE
引用块高亮内容闪卡会直接显示内容

### ISSUE THREAD

**Issue by AvoidantPerDis** [royc01/notion-theme#272]
![recording](https://github.com/royc01/notion-theme/assets/154863885/646aa0fc-1257-4c07-a17c-4ca5464c51f5)
以前用闪卡插件没这bug的，跟vv的插件也没有关系，应该是2.12新特性-闪卡高亮隐藏的原因

**Comment by royc01** [comment]
v3.8.8
