### ISSUE TITLE
全屏切换后按钮错位、状态栏遮挡数据库底栏

### ISSUE THREAD

**Issue by CKlimeths** [royc01/notion-theme#278]
在文档中切换为全屏后，按钮错位的问题
![image](https://github.com/royc01/notion-theme/assets/86591721/dd533686-0b08-41ba-a3fe-3d3d6baad646)
![image](https://github.com/royc01/notion-theme/assets/86591721/b101ca3d-4e79-4876-8b33-70c4a4679c40)

状态栏遮挡数据库的问题
![image](https://github.com/royc01/notion-theme/assets/86591721/1466b5c3-1fd2-4510-868b-3e98e437270e)
这种状态栏虽然很好看，但处理遮挡还是比较麻烦，要不做一个切换按钮？可以切换为默认主题那种的？这样就不用操心底部面板适配、遮挡内容、遮挡侧边面板这些问题了。

**Comment by royc01** [comment]
感谢反馈，下个版本修复，2的问题只能往上滚一点或者关了底栏了

**Comment by CKlimeths** [comment]
我找到第二个问题的解决办法了，把我不用的收集箱移动到底栏就可以了🤣
![image](https://github.com/royc01/notion-theme/assets/86591721/e2630de6-33b5-40f7-b767-6629b5ba213d)

**Comment by royc01** [comment]
v3.9.0
