### ISSUE TITLE
預覽列表中的錯誤

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-theme#28]
當鼠標懸停在紅色圖標上以查看隱藏列表時，會出現方塊。 注意圖標旁邊出現的兩個方塊！

![image](https://user-images.githubusercontent.com/90691302/195152854-6c791371-2c51-42d4-8fe0-0c74205f6085.png)

**Comment by royc01** [comment]
我这边重现不了，重新下载主题测试一下
