### ISSUE TITLE
优化「全部更新」按钮 UI

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#284]
[v3.0.5-dev2](https://github.com/siyuan-note/siyuan/releases/tag/v3.0.5-dev2) 新增了一个「[全部更新](https://github.com/siyuan-note/siyuan/issues/8390)」按钮，稍微有点丑：

![image](https://github.com/royc01/notion-theme/assets/78434827/188fcbae-adba-4161-94e9-c3303a03c869)

**Comment by royc01** [comment]
感谢反馈，下个版本v3.9.1修正
