### ISSUE TITLE
超级块组合下标题的样式错误

### ISSUE THREAD

**Issue by HarryHuaa** [royc01/notion-theme#285]
两个标题组成横向的超级块，段落再与其中一个标题组成纵向的超级块或
一个标题与段落组成纵向的超级块，另一个标题再与此超级块组成超级块均会有如图所示的样式错误
![image](https://github.com/royc01/notion-theme/assets/11732858/88e5d889-2177-4f84-99b0-15ac13c4fe87)
![image](https://github.com/royc01/notion-theme/assets/11732858/864b9edc-806a-47b6-8e34-f5726781d58c)

**Comment by royc01** [comment]
感谢反馈，下个版本v3.9.1修正
