### ISSUE TITLE
（反链里传递型双链的）首个子列表无法展开

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#288]
默认主题没有这个问题

![image](https://github.com/royc01/notion-theme/assets/78434827/746cb1e6-4d05-42bc-80e9-fb2da102ca9e)

**Comment by royc01** [comment]
我这边可以正常展开，下个版本更新再看看

**Comment by TCOTC** [comment]
感觉与 https://github.com/frostime/siyuan-center-width/issues/23 一样是与边距有关的问题

我把这个调到 50px 之后就能点击并展开了：

![image](https://github.com/royc01/notion-theme/assets/78434827/569fc607-6f3b-4b79-84bb-8e039f604921)

![image](https://github.com/royc01/notion-theme/assets/78434827/64186534-a0d0-4aa2-b4c5-5b4fed349a18)

![image](https://github.com/royc01/notion-theme/assets/78434827/32f3e269-c84a-4116-b2ae-f44c41bcd7ce)

**Comment by TCOTC** [comment]
刚刚发现原来是同一个问题，首个列表无法展开，但后面的列表就能展开了

**Comment by TCOTC** [comment]
点击之后就一直处于 `disabled="disabled"` 的状态没有变化了

![image](https://github.com/royc01/notion-theme/assets/78434827/ee1ca4c4-6d73-4500-9615-e97dc2857228)

**Comment by royc01** [comment]
还是没能复现，先不管了😞

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/42d98e45-f7ca-493a-b8cd-3f229f7d50ac)

**Comment by royc01** [comment]
v4.0.7

**Comment by TCOTC** [comment]
没完全修好，反链面板里可以展开了，但文档里的首个列表还是不能展开

**Comment by royc01** [comment]
> 感觉没完全修好，反链面板里可以展开了，但文档里的首个列表还是不能展开。
> 
> 不过也可能是思源的问题

我这边估计没啥办法了😅
