### ISSUE TITLE
数据库视图下方表示焦点的横条看不见了

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#290]
![image](https://github.com/royc01/notion-theme/assets/78434827/ca816f12-67c6-46db-b42c-37527e79fdf8)

默认主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/a102a3b6-027d-44c7-9a85-218bcab0d503)

**Comment by royc01** [comment]
感谢反馈，下个版本v3.9.1适配
