### ISSUE TITLE
在列表中把字列表设定为看板格式后，超出页面范围不能滑动查看

### ISSUE THREAD

**Issue by Allxy5** [royc01/notion-theme#292]
<img width="960" alt="截屏2024-04-23 00 18 35" src="https://github.com/royc01/notion-theme/assets/112512003/8e37e4ef-2773-4b8d-a961-9cbb2de65d47">
右边超出页面的内容看不了

**Comment by royc01** [comment]
这个暂时不支持列表里面的看板样式，后续应该不会优化了，等官方数据库的看板视图，感谢反馈
