### ISSUE TITLE
适配 v3.0.12 的文档标签新样式

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#294]
https://github.com/siyuan-note/siyuan/issues/10926

v3.0.12 的文档标签会变成这样：

在已添加的标签后有一个加号：

![image](https://github.com/royc01/notion-theme/assets/78434827/ee65cdef-da42-4bf6-828d-5612531f777b)

目前版本的主题会点不了加号、删不掉已添加的标签：

![image](https://github.com/royc01/notion-theme/assets/78434827/789935bd-64e8-4a74-a6b6-fde04d9a23d5)

这个很难点到：

![image](https://github.com/royc01/notion-theme/assets/78434827/acea7da4-53a7-4cfd-bdcb-8cfe9f41b6fb)

可以等 v3.0.12-dev4 或者 v3.0.12 出来之后再适配

**Comment by TCOTC** [comment]
相比 dev3 ，dev4 的加号多了文字：

![image](https://github.com/royc01/notion-theme/assets/78434827/ca9e357a-453b-46da-915f-a52583da9d0e)

![image](https://github.com/royc01/notion-theme/assets/78434827/6795a624-facb-4227-aae8-c58c19bcd546)

**Comment by TCOTC** [comment]
新版还是不好点击

**Comment by royc01** [comment]
> 新版还是不好点击

刷新一下缓存？

**Comment by TCOTC** [comment]
> > 新版还是不好点击
> 
> 刷新一下缓存？

原来还能这样
