### ISSUE TITLE
「视图选择」出现在数据库资源列链接菜单

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#298]
完全按照下面的操作可以复现：

[视图.webm](https://github.com/royc01/notion-theme/assets/78434827/99588a2e-c257-4982-90c6-21e5746af87f)

**Comment by royc01** [comment]
我复现不来，重新打开页面应该不会出现吧？

**Comment by TCOTC** [comment]
我研究半天也就上面那个步骤可以复现（每一次鼠标点击都不能省、不能错）

**Comment by royc01** [comment]
那先不管了，估计很少这样用
