### ISSUE TITLE
数据库属性面板属性名前显示图标

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#299]
不显示图标的话不太方便判断列类型：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/67a46401-15d8-4c18-952d-9f5ea1241948)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c42b49c7-db04-4126-b0b8-f654340fb5ec)

**Comment by royc01** [comment]
v3.9.6
