### ISSUE TITLE
列表第三级不能显示任务列表的复选框

### ISSUE THREAD

**Issue by charce526** [royc01/notion-theme#30]
如下图，一级、二级为有序列表，三级以后为任务列表，任务列表前面的复选框不显示（但是可以点击）：
![image](https://user-images.githubusercontent.com/25284381/195491805-8ff24e56-5ff8-47c2-95bf-3c848fc2ae6a.png)
如下图，一级、二级若是无序列表，则显示正常：
![image](https://user-images.githubusercontent.com/25284381/195491994-931a226e-fa9b-411d-94e7-0189759158f0.png)

**Comment by royc01** [comment]
下个版本修复，感谢反馈
