### ISSUE TITLE
底栏和提及面板的问题

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#301]
底栏：

![image](https://github.com/royc01/notion-theme/assets/78434827/2dc95d0e-0f77-43b4-adf8-97840f2320ab)

**Comment by TCOTC** [comment]
提及：

设置为 -1 收起面板：

![image](https://github.com/royc01/notion-theme/assets/78434827/220d0b38-7298-4819-aa04-6f6d13e37df7)

默认主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/743e4189-bc15-4517-ac0d-64b86f248845)

写味主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/e7d1707b-ea4b-4b5f-b317-45a752459b19)

**Comment by EvansSec** [comment]
所以对于v3.0.17中的底栏，在后续Savor的版本中是会隐藏掉的嘛？
<img width="919" alt="Snipaste_2024-06-04_11-11-52" src="https://github.com/royc01/notion-theme/assets/125636065/b6ab8e14-781a-4332-8777-b7b173e5710b">

**Comment by royc01** [comment]
v3.9.6

**Comment by TCOTC** [comment]
@royc01 还是会显示：

![image](https://github.com/royc01/notion-theme/assets/78434827/3b817db4-af50-483f-8d23-fc2fdd71198f)
