### ISSUE TITLE
请问 挖空 是什么

### ISSUE THREAD

**Issue by ouyang7923** [royc01/notion-theme#302]
![image](https://github.com/royc01/notion-theme/assets/105358618/feb16021-7e7a-42cc-966d-d0a25b1c4799)
一直无法理解，找不到说明，很是诧异

**Comment by TCOTC** [comment]
**标记文本**之后你再用这个功能，试试就知道了：

![image](https://github.com/royc01/notion-theme/assets/78434827/17a557f5-23be-4470-92b8-f5f60f1f6709)

使用 `挖空` 后：

![image](https://github.com/royc01/notion-theme/assets/78434827/4d35d4e8-3001-4d9a-ace5-55c63fb32138)
