### ISSUE TITLE
与 plugin-add-shortcut-to-topbar 插件冲突

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#304]
![image](https://github.com/royc01/notion-theme/assets/78434827/43eba760-8669-4f5d-97c2-36810b47503c)

主题更新后，按钮无法正常排序，并且会有错位：

![image](https://github.com/royc01/notion-theme/assets/78434827/1d73bab9-b911-4518-aea0-b0763a8f0f0b)

![image](https://github.com/royc01/notion-theme/assets/78434827/c35ca9e6-b848-4194-9b88-8becaab398b4)

**Comment by royc01** [comment]
v3.9.7

**Comment by TCOTC** [comment]
顶栏按钮不能显示到左边了（全在右边），而且会跟页签重叠

![image](https://github.com/royc01/notion-theme/assets/78434827/afd16288-093f-4e41-8c75-3ac880a1df84)

**Comment by TCOTC** [comment]
还不止这个问题，我关闭一个页签后能显示到左边了，但右边又错位了

![image](https://github.com/royc01/notion-theme/assets/78434827/4c1527c6-8f34-4f92-a180-253dd5e77984)
