### ISSUE TITLE
以前的标签页更好看

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#305]
这个感觉好丑：

![image](https://github.com/royc01/notion-theme/assets/78434827/ac09d746-0108-4119-a28f-b3e0796e658c)

**Comment by royc01** [comment]
与顶栏合并后这样的设计比较整体，但是sugar配色对比不太明显，我先调整试试，v3.9.7

**Comment by royc01** [comment]
v3.9.8
