### ISSUE TITLE
页签与顶栏重叠

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#306]
感觉上还是原来的更好，现在顶栏可利用的空间变少了

![image](https://github.com/royc01/notion-theme/assets/78434827/2fab444b-959a-4193-b285-82bd42f04d9e)

**Comment by royc01** [comment]
初衷是想和任我行的主题风格区分强烈一点，大屏使用的时候会简洁一点，我想想怎么把经典模式也做进去吧。

**Comment by royc01** [comment]
v3.9.8
