### ISSUE TITLE
需求：希望链接和附件支持图标

### ISSUE THREAD

**Issue by zhoutaosheng** [royc01/notion-theme#308]
类似下面这样，在链接前面给上图标
![image](https://github.com/royc01/notion-theme/assets/5683995/c65c815f-4914-47cc-9639-a769dfd5c642)

同时附件，也希望有图标展示（比如 pdf文件，给一个 pdf 图标）
> 注：上面是 Dark+ 主题的图标显示

**Comment by royc01** [comment]
这个之前做过但是不再维护了，直接使用插件市场里面的链接图标插件即可，感谢回复。

**Comment by zhoutaosheng** [comment]
> 这个之前做过但是不再维护了，直接使用插件市场里面的链接图标插件即可，感谢反馈。

ok，赞
