### ISSUE TITLE
菜单高度问题

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#312]
在菜单加了这些之后，菜单就变得需要滚动了：（应该自动向下拉长）

[滚动.webm](https://github.com/frostime/sy-bq-callout/assets/78434827/9976880c-7997-47c9-83b8-15d646c551f5)

关联：https://github.com/frostime/sy-bq-callout/issues/7

**Comment by royc01** [comment]
感谢反馈  v4.0.0调整
