### ISSUE TITLE
数据库筛选中的单选多选样式问题

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#313]
在数据库筛选里的样式跟其他地方不同：

![image](https://github.com/royc01/notion-theme/assets/78434827/ed577270-f615-47a3-82d6-bf221dfa783d)

其他地方：

![image](https://github.com/royc01/notion-theme/assets/78434827/1445af71-a684-4acb-a274-b160faf49dc3)

**Comment by royc01** [comment]
感谢反馈  v4.0.0修复
