### ISSUE TITLE
侧栏按钮配色问题

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#314]
我正在使用的是 https://github.com/siyuan-note/siyuan/releases/tag/v3.1.0-dev2

---

希望 Light 和 Sugar 配色下不要用黑色：

![image](https://github.com/royc01/notion-theme/assets/78434827/f2109b53-b125-42e8-89f4-77f0d02ad146)

以及焦点不在面板的时候，鼠标划过会闪烁：

[主题.webm](https://github.com/royc01/notion-theme/assets/78434827/3da1a148-bcf1-46cf-88c8-5662506c5312)

**Comment by royc01** [comment]
v4.0.0修改一下hover的颜色

**Comment by TCOTC** [comment]
这个黑色还是不好看
