### ISSUE TITLE
分屏后顶部菜单失效

### ISSUE THREAD

**Issue by CSMsamuel** [royc01/notion-theme#316]
我现在使用的是 [https://github.com/siyuan-note/siyuan/releases/tag/v3.1.0-dev2](https://github.com/siyuan-note/siyuan/releases/tag/v3.1.0-dev2)

https://github.com/royc01/notion-theme/assets/105100795/5825b80f-fbd8-4178-b253-c8d9f40353ef

**Comment by royc01** [comment]
感谢反馈  v4.0.0修复
