### ISSUE TITLE
反链提及的一点问题

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#317]
> 还是会显示：（我觉得收起面板的时候应该隐藏一下）
>
> ![image](https://github.com/royc01/notion-theme/assets/78434827/3b817db4-af50-483f-8d23-fc2fdd71198f)

_Originally posted by @TCOTC in https://github.com/royc01/notion-theme/issues/301#issuecomment-2156704674_

发现侧栏取消钉住的时候这个问题会很明显：

![image](https://github.com/royc01/notion-theme/assets/78434827/9f9fd7b5-9fc5-4481-801f-40499d535f38)

默认主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/d7d201a2-fee3-4df4-9c87-5d5e0a078698)

**Comment by royc01** [comment]
v4.0.1调整
