### ISSUE TITLE
侧栏按钮配色问题

### ISSUE THREAD

**Issue by CSMsamuel** [royc01/notion-theme#319]
目前使用的版本是 v3.1.0-dev3。

侧栏不钉住时离开侧栏按钮图标转黑。
侧栏钉住时这一现象不发生。

https://github.com/royc01/notion-theme/assets/105100795/82417665-00bb-4a4d-a16f-632ee27568ac

**Comment by royc01** [comment]
应该跟钉住无关，dock栏的图标激活状态背景颜色是黑的，设计如此
