### ISSUE TITLE
块嵌入列表线没有完美对齐

### ISSUE THREAD

**Issue by HowcanoeWang** [royc01/notion-theme#32]
2.4.0版本

有问题的示例：
<img width="619" alt="image" src="https://user-images.githubusercontent.com/19968935/195746670-75b36963-c1c6-419a-99ac-3290f80c0f9a.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/19968935/195746914-6bbc6b9a-9c75-4add-a24e-39e4142a4415.png">

没问题的示例：
<img width="499" alt="image" src="https://user-images.githubusercontent.com/19968935/195746785-4db8b8cc-2c07-4bf4-aca1-7a0c40fd0c9d.png">

另外，这个块嵌入感觉还是有些突兀。比如稍微降低背景色透明度？（wolai那样的完全只保留左侧竖线感觉又太不明显了）

<img width="366" alt="image" src="https://user-images.githubusercontent.com/19968935/195747296-f4f8ccbb-7bb8-4b43-b02f-192e95e392ec.png">

**Comment by royc01** [comment]
了解，后续看看怎么优化

**Comment by royc01** [comment]
样式微调了一下，列表官方没有对齐，后面再考虑吧

**Comment by HowcanoeWang** [comment]
https://github.com/siyuan-note/siyuan/issues/6266#issuecomment-1283961190

> 默认主题的引述块存在 padding 和 border，除非移除这些样式，否则没有办法对齐。

似乎可以通过设置data-type="NodeBlockEmbed"的padding-left=0来实现对齐块引用的对齐？

![image](https://user-images.githubusercontent.com/19968935/196703747-53d23c71-824a-49c2-9ea2-5a3428768274.png)

![image](https://user-images.githubusercontent.com/19968935/196703399-2af4018b-e9f9-47d0-94cd-e9270bd12147.png)

调节之前：

![image](https://user-images.githubusercontent.com/19968935/196704066-c2f422bf-9df4-460e-885e-05559cc18daa.png)


调节之后：



![image](https://user-images.githubusercontent.com/19968935/196703201-32d241cf-886f-45b5-919f-7e0b697060f7.png)

**Comment by HowcanoeWang** [comment]
但上述情况仅适用于 主页面 下的嵌入块

对于列表项内部的嵌入块，不改这个padding-left=4是正确的

![image](https://user-images.githubusercontent.com/19968935/196705189-24666f3f-422c-4635-9e1d-729b920d907c.png)

改了反而不对了

![image](https://user-images.githubusercontent.com/19968935/196705358-386bd8b9-814a-4502-95cb-0e9286cbd7fb.png)

**Comment by royc01** [comment]
`padding-left:2px;`试试

**Comment by HowcanoeWang** [comment]
> `padding-left:2px;`试试

2的话，对的还不是很完美

![image](https://user-images.githubusercontent.com/19968935/196713121-c9a739da-a7e4-40a7-9c2d-9cc2c41c33e9.png)
