### ISSUE TITLE
新版本左右分屏情况下，右上角标签和系统按钮重叠

### ISSUE THREAD

**Issue by zhengxiang0808** [royc01/notion-theme#320]
![image](https://github.com/royc01/notion-theme/assets/18425560/c91f8623-b69a-46ec-b7b2-95121a37b662)

**Comment by royc01** [comment]
感谢反馈，v4.0.2调整一下

**Comment by zhengxiang0808** [comment]
您好，更新到最新版本之后，之前重叠的情况没有了，但页签会将功能按钮覆盖：
![image](https://github.com/royc01/notion-theme/assets/18425560/92a0e478-3c39-45bb-b52e-061e84507194)
通过向右拖拽分栏线，右侧分栏页签会右移，然后将功能按钮给覆盖了：
![image](https://github.com/royc01/notion-theme/assets/18425560/b393b8e8-dafc-45ac-9f12-1d370a71908a)
我记得之前顶栏是可以设置为向上隐藏的，但是现在逻辑变成了“顶栏合并”，个人感觉之前的设计更好，这个您考虑一下哈~
