### ISSUE TITLE
分屏时，PDF 打开侧栏后无法拖拽页面宽度

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#322]
这个是 https://github.com/siyuan-note/siyuan/issues/11759 中的情况，更新 v3.1.0-dev5 之后我发现默认主题没问题了，但使用 Savor 主题还有这个问题。

试过在开发者工具 Ctrl+Shift+R，还是一样。

关闭侧栏时是正常情况：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/82f35432-2d3a-451a-a857-9156ab54417b)

打开侧栏后，这里就无法拖动了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7c280f2f-9c1f-46f5-b102-2ccb890ee18a)

**Comment by royc01** [comment]
v4.0.2修复
