### ISSUE TITLE
折叠状态下的列表块会显示####

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#326]
将列表块折叠后，会在右侧和下方出现两个`####`标志，鼠标悬浮上去后显示该列表块
![recording](https://github.com/royc01/notion-theme/assets/43239563/26d00a1b-820a-4f1a-afc5-984b8c0187dc)
注：列表块刚折叠时不会出现这种情况，需要刷新一下界面

**Comment by royc01** [comment]
复现不了，是不是加了啥插件或者代码片段？

**Comment by QMike0** [comment]
还真是，把代码片段关了就正常，原因是用代码片段修改了超链接的样式，`color`后面加了`!important`，因此强制显示了折叠的列表后的省略号所带的链接（Savor特有）
不过测试了一下，好像主题自带的`列表折叠悬浮显示`这个功能存在问题。鼠标悬浮在折叠的列表后的省略号上，只能显示当前的未折叠内容，不能显示下方折叠区域的内容，如下（已关闭插件和代码片段）：
![recording](https://github.com/royc01/notion-theme/assets/43239563/7301508c-7213-4281-baec-d27c622e347e)

**Comment by royc01** [comment]
v4.0.3优化一下
