### ISSUE TITLE
顶栏合并状态下，插件按钮区域能否默认展开

### ISSUE THREAD

**Issue by QMike0** [royc01/notion-theme#328]
当前顶栏合并状态下，插件按钮区域是默认折叠的：
![image](https://github.com/royc01/notion-theme/assets/43239563/6af51a51-b65a-4c39-aead-ca53a2d30af4)
实测即使页签开启很多的状态下，并不会占用插件按钮区域（这一点好像和Asri主题不同）：
![image](https://github.com/royc01/notion-theme/assets/43239563/1a40471f-1aad-4f28-a10e-c69a2abd38e2)
既然插件按钮的展开与否并不影响页签，个人感觉该区域默认为展开状态可能更好一些，不然每次进入思源后要手动点击展开

注：还有个问题，若上次退出思源时，插件按钮区域若是展开状态，本次进入思源时`展开插件`按钮显示向右：
![image](https://github.com/royc01/notion-theme/assets/43239563/6c96877b-b2c0-4253-a644-15cdb0e0eda0)
就需要点击两次按钮才能展开该区域

**Comment by royc01** [comment]
v4.0.3修复
