### ISSUE TITLE
[BUG] 页签和插件较多，插件会被页签遮挡

### ISSUE THREAD

**Issue by lisontowind** [royc01/notion-theme#329]
![image](https://github.com/user-attachments/assets/6b212294-ced4-4657-8c12-a714ca6b8070)
![image](https://github.com/user-attachments/assets/af1bf5da-4a91-4f7a-9c5b-ad5f8d4c55cb)
如图，都挡住了

**Comment by lisontowind** [comment]
![QQ_1721733023640](https://github.com/user-attachments/assets/e67ef418-af78-4c35-97fc-82d6c171a0cd)
同时提示会导致页签的层级露馅。。。。

**Comment by royc01** [comment]
v4.1.2换一种实现方式先试试看
