### ISSUE TITLE
列表项中的嵌套引述块异常缩进

### ISSUE THREAD

**Issue by rwaysov** [royc01/notion-theme#330]
Savor主题版本：v4.0.6
使用官方的daylight主题时，列表项中的嵌套引述块显示如下：
![image](https://github.com/user-attachments/assets/47e2060e-a137-4ad2-a5e7-9f54ce838b64)
但是使用Savor主题时，显示如下：
![image](https://github.com/user-attachments/assets/5d398640-15a7-42d2-a141-b3890a1987cc)

期望：列表项中的嵌套引述块不需要缩进那么多，按照官方的daylight主题的方式显示会比较好。

**Comment by royc01** [comment]
v4.0.7
