### ISSUE TITLE
v3.1.4 有可能需要适配代码块样式

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#331]
DOM 改动：https://github.com/siyuan-note/siyuan/issues/10769

![image](https://github.com/user-attachments/assets/9c484fcc-3429-446a-821d-1e692bf3fc3b)

**Comment by Vanessa219** [comment]
这个是怎么弄出来的？

**Comment by TCOTC** [comment]
@Vanessa219 这里是主题的仓库了

**Comment by royc01** [comment]
v4.0.7
