### ISSUE TITLE
[改进] 按钮似乎有点错位

### ISSUE THREAD

**Issue by lisontowind** [royc01/notion-theme#337]
![image](https://github.com/user-attachments/assets/f4f6e725-19bf-4785-852b-5053479845e9)
![1725351799909](https://github.com/user-attachments/assets/d7302ce9-80a7-43f6-a750-24274c4a73ed)

按钮似乎有点小小错位，不知道是不是故意设计成这样的，但我觉得似乎可以改进一下
调整了一下数值感觉好了
原来的数值
#Splugin {
    padding: 0px;
    margin-left: -54px;
    width: 20px;
    height: 20px;
    margin-top: 3px;
    border-radius: 50%;
}
改之后的数值
#Splugin {
    padding: 0px;
    margin-left: -54px;
    width: 19px;
    height: 19px;
    margin-top: 2px;
    border-radius: 50%;
}

**Comment by royc01** [comment]
感谢反馈，这按钮有重大bug给重构一波了，Savor v4.1.4修复
