### ISSUE TITLE
最新主题在浏览器显示错误

### ISSUE THREAD

**Issue by heartacker** [royc01/notion-theme#338]
https://github.com/royc01/Odyssey/issues/12#issue-2505613928

**Comment by heartacker** [comment]
![image](https://github.com/user-attachments/assets/e27c48c4-72bf-43c3-a263-f1e492c8ca26)

**Comment by royc01** [comment]
感谢反馈，v4.1.5修复

**Comment by heartacker** [comment]
安卓浏览器还是不ok![Screenshot_20240906-001147.png](https://github.com/user-attachments/assets/14a675a0-9ba0-4e57-b3bb-c475a62b8171)

**Comment by heartacker** [comment]
清理缓存好了
