### ISSUE TITLE
[bug]更新v4.1.6，显示异常，客户端版本V3.1.5最新版本

### ISSUE THREAD

**Issue by code-lixm** [royc01/notion-theme#339]
<img width="183" alt="image" src="https://github.com/user-attachments/assets/4c0a0b91-3219-41d0-b71b-f4a05de5357d">

**Comment by royc01** [comment]
是否使用了移除按钮插件之类的？

**Comment by code-lixm** [comment]
> 是否使用了移除按钮插件之类的？

是的

**Comment by royc01** [comment]
> > 是否使用了移除按钮插件之类的？
> 
> 是的，但是使用4.1.1是好的，后面都会这样了

暂时只能这样了，后面研究怎么适配一下

**Comment by royc01** [comment]
v4.1.7修复
