### ISSUE TITLE
一点个人的建议：重命名主题，日历无法点击今日跳转到今日日记

### ISSUE THREAD

**Issue by EberhardLin** [royc01/notion-theme#34]
## 重命名主题
作者原有主题三合一（Notion-Theme，Notion-Dark，Salt三个主题合并在Notion-Theme主题中）后，继续采用Notion-Theme命名是否会有些不妥，尤其是这个[更新提醒](https://github.com/royc01/notion-theme#%E6%9C%89%E4%BD%BF%E7%94%A8dark-salt%E4%B8%BB%E9%A2%98%E7%9A%84%E6%9C%8B%E5%8F%8B%E8%AF%B7%E7%9B%B4%E6%8E%A5%E6%8D%A2%E5%88%B0%E6%AD%A4%E4%B8%BB%E9%A2%98%E5%85%B6%E4%BB%96%E4%B8%BB%E9%A2%98%E5%90%8E%E7%BB%AD%E4%BC%9A%E5%81%9C%E6%9B%B4)没有置顶在主题介绍最上方，容易让不关注这个主题更新的人产生迷惑。所以是不是可以考虑为新主题命名一个新的名字，例如「Notion-Salt」，并考虑更新主题介绍，这样既可以统一规范的为介绍该主题。

## 日历点击跳转问题
日历功能可以很好的通过点击跳转到当月有所「日记」那一天，但当天却不能跳转，我不知道是不是我的问题，所以在这里提一下。

**Comment by royc01** [comment]
1、下个版本官方主题会有大更，所以细化部分后续补上，先做主题适配
2、日历功能有滞后性，需要重新加载一遍才可以跳转，建了当天笔记后，重开一下思源应该就可以点了

**Comment by EberhardLin** [comment]
> 1、下个版本官方主题会有大更，所以细化部分后续补上，先做主题适配 2、日历功能有滞后性，需要重新加载一遍才可以跳转，建了当天笔记后，重开一下思源应该就可以点了

好的，非常感谢你的回复，主题使用体验很好，尤其是Salt主题，再次感谢。
