### ISSUE TITLE
[BUG]右上角图标重叠

### ISSUE THREAD

**Issue by maxkiicc** [royc01/notion-theme#343]
SiYuan: v3.16
插件版本: v4.1.6

Macbook m1 右上角按钮图标有重叠

<img width="411" alt="image" src="https://github.com/user-attachments/assets/2911d742-0184-4bf5-a287-0a610ada6826">
<img width="334" alt="image" src="https://github.com/user-attachments/assets/d0e87739-a84f-4635-b895-84af6cf5c278">

**Comment by royc01** [comment]
感谢反馈，v4.1.7修复
