### ISSUE TITLE
暗黑模式下使用背景插件时侧栏无颜色

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [royc01/notion-theme#344]
在暗黑模式下，使用背景插件修改了背景的话，如果侧栏不钉住的话侧栏位置就会直接透明显示背景图片，这个有时候会影响到侧栏按钮的显示，这种情况是有意为之的吗？还是因为插件修改了样式引起的呢？
下附截图显示一种极端情况。
![Clip_2024-09-15_12-16-12](https://github.com/user-attachments/assets/20468cfa-ad23-4ce7-b17e-300937189941)

**Comment by royc01** [comment]
v4.1.8修复
