### ISSUE TITLE
顶栏合并，插件图标位置错乱

### ISSUE THREAD

**Issue by KuangJieRepository** [royc01/notion-theme#346]
**异常显示：**
![截图_20240918092931](https://github.com/user-attachments/assets/6d2015fc-f35f-4247-93bb-8cc7bb7e907c)
**主题版本：**
![截图_20240918093020](https://github.com/user-attachments/assets/d415876e-ac29-4d96-80ad-428ecf740894)
**思源版本：**
![截图_20240918093047](https://github.com/user-attachments/assets/9b8f9281-cd2a-4653-a600-61c80bee27b2)

**Comment by royc01** [comment]
重开一下思源应该正常

**Comment by KuangJieRepository** [comment]
不行，我电脑刚开机，然后刚重启一下还是错乱。
还会提示这个：
![截图_20240918094648](https://github.com/user-attachments/assets/24d3b44f-9957-4060-8458-9e109756a678)

**Comment by royc01** [comment]
没有足够空间是备注插件之类的原因吧，有空位是取消钉住的问题，我再适配一下

**Comment by royc01** [comment]
v4.1.9
