### ISSUE TITLE
希望数据库的筛选和排序按钮保留背景色

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#347]
默认主题下，数据库有筛选或排序时的样式，很方便判断：

![image](https://github.com/user-attachments/assets/841efe52-ec09-4e66-9bb7-5ee0712295be)

但用 Savor 之后这部分代码把背景色变透明了：

https://github.com/royc01/notion-theme/blob/a2c6d7981a48964040344114f6854591657c58d0/style/module/menu.css#L187-L189

![image](https://github.com/user-attachments/assets/72e280e7-2a5e-465e-a459-09870e2bd811)

**Comment by royc01** [comment]
感谢反馈，v4.2.0修复
