### ISSUE TITLE
视图转化 按钮消失

### ISSUE THREAD

**Issue by gingde** [royc01/notion-theme#348]

**Comment by gingde** [comment]
当前版本 v3.1.7  ；思源笔记
savor 写未主题，视图转化按钮消失
这个问题还是比较容易出现的。
1. 之前有因为个别插件 导致这个视图转化 功能消失：  便利贴插件
2. 有时候 可能会消失一会儿，重启软件后就可以了
3. 这次3.1.7安装包更新后，这个视图转化 按键就消失了，卸载主题重装也没用。关闭所有插件也没用。

**Comment by Myeongho8888** [comment]
我也遇到了完全一样的问题，期待作者大大更新~

**Comment by royc01** [comment]
感谢反馈，v4.2.0修复
