### ISSUE TITLE
界面优化：数据库的引用链接样式可以更直观吗？

### ISSUE THREAD

**Issue by luluciamk** [royc01/notion-theme#350]
如图，现在数据内的“引用链接”和普通文本 是同一个标志，完全无法分辨
大大可以修改数据库里面这个引用链接样式，使其变得直观吗？
![image](https://github.com/user-attachments/assets/b4a61ee9-7bb6-4e77-9d0b-5778d5674582)
变成类似这种，颜色可以亮一点吗（请不要加图标，因为数据库的表格框很窄，加了图标很拥挤）
![image](https://github.com/user-attachments/assets/ededd513-ee73-4640-b0db-310d8a0347c2)

**Comment by royc01** [comment]
下个版本调整为加粗，但不调整颜色了，感谢反馈
