### ISSUE TITLE
我的侧边栏感觉不太对，和写味配色图不一样啊，怎么回事

### ISSUE THREAD

**Issue by tianxia704** [royc01/notion-theme#351]
我的侧边栏是这样，
<img width="530" alt="image" src="https://github.com/user-attachments/assets/761a5fff-89d2-4c29-8ff4-09d4bdc3605e">

写味的带个阴影，还有所区分。
![image](https://github.com/user-attachments/assets/4c29bee8-7fd7-46cd-ab96-604de4ea2a45)

我觉得稍微区分的好看些，怎么回事呢

**Comment by royc01** [comment]
你好，截图是早期的设计方案，现在已经不用了，感谢反馈
