### ISSUE TITLE
下拉栏被全屏挂件遮挡

### ISSUE THREAD

**Issue by Nyeilim** [royc01/notion-theme#352]
见图片右上角区域，在使用其他系统下拉栏时候，没有这个问题
使用挂件为 Whiteboard，在引入时会默认铺满全屏
![image](https://github.com/user-attachments/assets/74b1d2a5-5140-49cb-bef6-a8ecbdb6470c)
![image](https://github.com/user-attachments/assets/da148575-6617-44a4-a2ea-13ed98d73cea)

**Comment by royc01** [comment]
感谢反馈，v4.2.4版本看看

**Comment by Nyeilim** [comment]
![image](https://github.com/user-attachments/assets/78bfd17e-8ee7-43b5-ae92-756510ee71d4)
v4.2.5 版本还是会存在这个问题，和其他插件/挂件的 UI 界面会有交叠问题。图示为反向过滤面板插件的 Dock。
我看其他插件的下拉框是可以做到的，下图为 “目录插件” 的下拉框，不知道能不能对开发有帮助。
![image](https://github.com/user-attachments/assets/4ebce3fc-34b1-4558-88b9-c01c9e8ece5d)
