### ISSUE TITLE
界面展示中，数字和字母使用的字体与设置的字体不一致

### ISSUE THREAD

**Issue by rwaysov** [royc01/notion-theme#354]
思源版本：v3.1.9 Windows版
操作系统：Win11 23H2
主题版本：v4.2.0
外观模式：明亮

在设置中设置了字体为「Microsoft YaHei」：
![image](https://github.com/user-attachments/assets/b1ecb869-57a4-45fd-96b7-cb7afe491f52)

设置了之后，编辑区中的文字的确使用了微软雅黑字体，其他区域，例如「文档树」、「大纲」、「书签」中的中文也使用了微软雅黑字体，但是这些区域中的数字和字母使用的字体不是微软雅黑，如下面的图片所示。

使用官方daylight主题时，大纲中的数字和字母使用的是微软雅黑字体：
![image](https://github.com/user-attachments/assets/c8f9c246-4873-42ba-9468-96e66c459eac)

使用写味主题时，大纲中的数字和字母使用的不是微软雅黑字体：
![image](https://github.com/user-attachments/assets/e15469eb-a17c-4f61-9de9-2f069ca091f1)

**Comment by royc01** [comment]
你好，界面字体只能通过css修改，
![image](https://github.com/user-attachments/assets/68630df1-47e0-45fd-b6f6-755f0209ffd8)
