### ISSUE TITLE
ipad 端进入全屏模式后，无法退出

### ISSUE THREAD

**Issue by Marcus-dba** [royc01/notion-theme#36]
ipad 端，一旦进入了全屏模式阅读，就无法退出，没有退出按键。
请帮忙紧急修复

**Comment by Marcus-dba** [comment]
windows端也这个情况，每次进入全屏模式，退出只能关闭重启，很影响体验，大佬求助

**Comment by royc01** [comment]
顶栏隐藏是特性，左右上角应该可以都触发，同时也加入了一键锁定顶栏的功能

**Comment by Marcus-dba** [comment]
> 
取消锁定就可以看到了。多谢
