### ISSUE TITLE
对于表格样式的后续请求~

### ISSUE THREAD

**Issue by Myeongho8888** [royc01/notion-theme#361]
感谢作者大大更新，效果好多了。不过在更新后，“无表头样式”的表格嵌套在“引述块”里面的“表头”样式还是需要完善一下，详见下图：

<img width="771" alt="截屏2024-11-13 20 46 11" src="https://github.com/user-attachments/assets/57d1bf49-1cb2-4e04-b2f5-b22f0c49567c">
<img width="772" alt="截屏2024-11-13 20 46 33" src="https://github.com/user-attachments/assets/67442292-f6fb-4451-a00f-d5de9ade2764">

辛苦作者大大了~

**Comment by royc01** [comment]
感谢反馈，v4.2.6版本修正
