### ISSUE TITLE
代码块渲染位置错误

### ISSUE THREAD

**Issue by Nyeilim** [royc01/notion-theme#365]
如下面的代码块，从视觉效果来看，是和 9 列表项同级的，但是其实它是属于 9 列表项的子块，没有正确缩进。
切换到默认主题可以正确显示
![image](https://github.com/user-attachments/assets/03471bd1-228b-4fb8-a80b-5cd643530334)
![image](https://github.com/user-attachments/assets/1dc37a34-c525-422f-a003-4e7794598754)

**Comment by royc01** [comment]
你好，这个在新版本v4.2.6已经修复，可以更新后刷新看看，感谢反馈
