### ISSUE TITLE
Salt 配色下使用“顶栏合并”，关闭符号无法正常显示

### ISSUE THREAD

**Issue by Nyeilim** [royc01/notion-theme#366]
如图，注意最右侧的关闭符号
![image](https://github.com/user-attachments/assets/1bec9ec3-a61e-480c-a45c-a1d56dcdf94a)

**Comment by Nyeilim** [comment]
还有上次那个下拉栏 Issue 的修复没有生效 #352

**Comment by royc01** [comment]
v4.2.7修复，感谢反馈
