### ISSUE TITLE
垂直页面和顶栏合并有冲突

### ISSUE THREAD

**Issue by Zolliner** [royc01/notion-theme#368]
同时开启垂直页面和顶栏合并，效果是这样的，重叠在一起了：
![图片](https://github.com/user-attachments/assets/b754828e-1bff-4832-864d-5a862cc3b72d)

同时，如果换成salt配色，是这样的，看不到部分按钮了：
![图片](https://github.com/user-attachments/assets/ed31d840-5edc-438f-be7d-beaa959e5dc3)

这两个功能都很喜欢，希望能优化一下，感谢

当前版本v4.2.7

**Comment by Zolliner** [comment]
以及，垂直页面和顶栏合并同时开启的时候，此时如果打开右侧栏的一个窗口（比如关系图或者全局关系图），再关闭，会有惊喜，出现大段空白：
![图片](https://github.com/user-attachments/assets/deb672f1-6cfb-4fa8-99fb-7c5b82af06b9)

**Comment by Zolliner** [comment]
关闭顶栏合并解决一切问题，综合考虑我还是关闭了，毕竟现在合并顶栏不会改变编辑页面的高度

**Comment by royc01** [comment]
这个暂时还没有什么好办法优化，只能不能同时使用了

**Comment by royc01** [comment]
v5.0.2改为不可同时使用
