### ISSUE TITLE
Salt 配色下使用“顶栏合并”，关闭所有页签后顶栏显示异常

### ISSUE THREAD

**Issue by Nyeilim** [royc01/notion-theme#369]
![image](https://github.com/user-attachments/assets/ca23891d-ceb7-40fc-adea-09217b79ec13)
![image](https://github.com/user-attachments/assets/ea771ff7-fee2-46df-9ca2-6d459bcfa12d)
上图为 Salt 配色下的顶栏显示，显示异常
下图为 Sugar 配色下的顶栏显示，显示正常
如果此时关闭左侧 Dock，左上角 SIYUAN 图标会越界显示，两种配色都有这个情况
![image](https://github.com/user-attachments/assets/c8736e10-6f14-4ae3-91dd-46b4d370cf53)

**Comment by royc01** [comment]
感谢反馈，v5.0.0重构版本应该没问题了
