### ISSUE TITLE
2.4.1新版本主题BUG

### ISSUE THREAD

**Issue by jimmyyukio** [royc01/notion-theme#37]
![图片](https://user-images.githubusercontent.com/60495173/196065165-ea359945-5780-47e5-8f90-14da18b7a808.png)
在今天更新2.4.1新版本后，主题显示出现问题

**Comment by royc01** [comment]
已更新

**Comment by XinLi0111** [comment]
已更新 2.5.3主题，仍然显示大图标。但是切换相反的模式后图标缩小

**Comment by royc01** [comment]
![QQ截图20221017170311](https://user-images.githubusercontent.com/38906705/196136409-d9e93f13-e2f0-41d0-9ae8-911628f99066.jpg)

**Comment by XinLi0111** [comment]
> ![QQ截图20221017170311](https://user-images.githubusercontent.com/38906705/196136409-d9e93f13-e2f0-41d0-9ae8-911628f99066.jpg)

👍，感谢感谢。一直在用 salt，非常漂亮。
