### ISSUE TITLE
添加标签加号与已有标签不平齐

### ISSUE THREAD

**Issue by gradypark86** [royc01/notion-theme#370]
添加标签的加号会比已有标签略高一些。
<img width="388" alt="image" src="https://github.com/user-attachments/assets/3bd3870b-93eb-447f-ba61-6e6bbda3097d">

**Comment by royc01** [comment]
感谢反馈，v5.0.0重构版本应该没问题了

**Comment by gradypark86** [comment]
非常感谢，试用了一下，确实解决了对齐问题。

小建议：
当前不含标签页面的 <kbd>添加标签</kbd> 按钮位于左上角：
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/c1c99073-fc12-4700-ae71-853eb10a6a44">
添加标签后 <kbd>添加标签</kbd> 按钮变到了右上角：
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/705872ae-c500-48e5-aae7-ddafe141ac7a">

在最初添加标签时感觉有些割裂，特别是思源 3.1.15 版本后[新增标签列表会持续展示](https://github.com/siyuan-note/siyuan/issues/13311)（如上图所示，标签列表在左侧依然展示，而右侧为已添加标签），不知能否将无标签页面的 <kbd>添加标签</kbd> 按钮修改至右上角呢？

**Comment by royc01** [comment]
如果这么改的话，有点反直觉，我再研究看看
