### ISSUE TITLE
思源v3.1.14版本，“转换为看板” 不再为横向结构

### ISSUE THREAD

**Issue by aobatu** [royc01/notion-theme#373]
思源版本：v3.1.14 
Savor版本：v4.2.7

问题描述：原先“转换为看板”功能是把列表横向排列，但是新版本更新后，看板变成竖向排列了，请问下是否可以恢复到原先横向的模式吗？
![image](https://github.com/user-attachments/assets/7e4edfbe-39c7-4036-9e4c-e66755a0bde8)

**Comment by royc01** [comment]
最近在重构主题，版本bug会搁置一阵，大概一周后可以上线全新版本

**Comment by aobatu** [comment]
> 最近在重构主题，版本bug会搁置一阵，大概一周后可以上线全新版本

好的。全新版本中，看板会恢复到原先的横向排列不？

**Comment by royc01** [comment]
v5.0.0重构版本上线测试看看
