### ISSUE TITLE
Salt 配色下侧边栏的面板有黑框

### ISSUE THREAD

**Issue by Hzz-0802** [royc01/notion-theme#376]
v5.0.1，在2台电脑上如此，并排除了代码片段影响。

![2024-12-09_213810](https://github.com/user-attachments/assets/274895ef-4ed7-4104-be60-2c0f0b09489f)
![2024-12-09_213204](https://github.com/user-attachments/assets/009a7a41-f40e-4fa4-b4e7-4b74821e519e)

**Comment by royc01** [comment]
设计如此，或者下个版本改个配色

**Comment by royc01** [comment]
v5.0.3调整salt配色
