### ISSUE TITLE
当用代码片段“隐藏标签栏的加号按钮”时“页签切换按钮”也被连坐隐藏了

### ISSUE THREAD

**Issue by Hzz-0802** [royc01/notion-theme#377]
v5.0.1，CSS代码如下

/** 隐藏标签栏的加号按钮 **/
```
.layout__center ul.layout-tab-bar:last-of-type li {
    display: none!important;
}
```

**Comment by royc01** [comment]
这个写法有误，可以改为
`.layout__center .fn__flex-column>.fn__flex>.layout-tab-bar [data-type="new"]{
    display: none!important;
}`
