### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by ioypl** [royc01/notion-theme#379]

**Comment by ioypl** [comment]
![PixPin_2024-12-10_23-26-45](https://github.com/user-attachments/assets/a9b4b595-edaa-46d4-8d31-c43e19144023)
右边这个侧栏是干什么用的？

**Comment by royc01** [comment]
没用，点一下侧栏的按钮开展收缩就消失，如果知道怎么复现的可以告诉我一下

**Comment by royc01** [comment]
复现不了就先关闭了
