### ISSUE TITLE
日历视图能否匹配所有类型的文档，而不仅仅是日记

### ISSUE THREAD

**Issue by mingyong-g** [royc01/notion-theme#38]
### 如题：日历视图能否匹配所有类型的文档，而不仅仅是日记
- 个人没有写日记的习惯，但是想通过日历看板回顾最近新建的文档记录，目前日历看板仅能关联日记，能否支持所有文档，并关联文档的创建日期
- 第二提一个个人想法，能否在1的基础下，做一个类似github提交记录的热力图？

**Comment by royc01** [comment]
1、现有的日历看板是建立在大佬的挂件上生成的，仅匹配2022-10-17这种格式的文档标题
2、跟1一样，热力图也要大佬做出来才挂上去，这个暂时做不了

**Comment by mingyong-g** [comment]
日历视图的挂件我看挂件市场已经有了，只是需要插入到文档中，使用起来没有notion-theme添加的日历看板方便

**Comment by royc01** [comment]
后面再研究吧  先顶顶

**Comment by mingyong-g** [comment]
可以的，也不是刚需，只是觉得日历看板这个功能非常nice👍👍👍如果能丰富一下就更好了
