### ISSUE TITLE
这次主题更新后，字体的设置不是在theme.css了吗？我这里修改代码字体无效

### ISSUE THREAD

**Issue by xybio** [royc01/notion-theme#380]

**Comment by xybio** [comment]
![image](https://github.com/user-attachments/assets/3d3ad6ed-8315-483f-94ea-530220ed2c0c)

**Comment by royc01** [comment]
新版本再测试下

**Comment by xybio** [comment]
> 新版本再测试下

没明白，我昨天更新的新版本。意思是重装，还是等下个版本？谢谢

**Comment by royc01** [comment]
抱歉没说明白，刚上了v5.0.6 🌞
