### ISSUE TITLE
Salt 配色下顶栏过宽且插件按钮显示异常

### ISSUE THREAD

**Issue by Nyeilim** [royc01/notion-theme#381]
![image](https://github.com/user-attachments/assets/20794f2e-202c-486f-a0c6-1ed8fa3d980b)
如图，可以在 Light 和 Salt 配色间切换下，能发现两种配色的顶栏宽度不同。然后右边的插件按钮也没正常显示。

碎碎念与建议：
现在 Salt 配色外边框改成淡灰了嘛？还挺喜欢以前的黑色，外黑内白注意力能够聚焦于编辑内容，同时编辑内容也不是全白不伤眼，这也是我喜欢 Salt 配色的原因。
另外建议引述块能够添加背景色【虽然我自己用代码片段添加了】，因为单看文字内容的话，并不能很直观地看出这是普通段落块还是引述块，而视线要扫到左边的引述块的 | 才知道。下面放两张对比图
![image](https://github.com/user-attachments/assets/fa42a6b3-0300-4ed7-88eb-db58372e5828)
![image](https://github.com/user-attachments/assets/d237388c-833b-48ef-8ad3-76597308c491)

**Comment by royc01** [comment]
1、配色问题刚上传了小版本应该修了。
2、因为现在的结构，外框的黑色占比过于大，所以调整为现在的样式。
3、引述块我再斟酌一下。
感谢反馈

**Comment by royc01** [comment]
顶栏高度不同也是是因为结构问题，现在还没有更好的解决办法，先顶顶

**Comment by royc01** [comment]
![image](https://github.com/user-attachments/assets/5d22ad7b-e778-45f2-b37f-0ebed8ae5cdf)
新版改成这个配色，应该可以满足
