### ISSUE TITLE
最新版，数据库

### ISSUE THREAD

**Issue by JHPZ** [royc01/notion-theme#382]

**Comment by JHPZ** [comment]
Uploading QQ20241211-183030.mp4…

**Comment by JHPZ** [comment]
https://github.com/user-attachments/assets/f87b4344-62e9-4462-8cb1-34d236211cf1

这里

**Comment by royc01** [comment]
你好最新版本v5.0.7应该是没问题的

**Comment by JHPZ** [comment]
欸 ，我是官方安装的 5.0.3
