### ISSUE TITLE
是否可以通过主题解决浏览器隐藏title 后显示的问题

### ISSUE THREAD

**Issue by heartacker** [royc01/notion-theme#383]
https://github.com/siyuan-note/siyuan/issues/13226

![image](https://github.com/user-attachments/assets/66bf1c5b-787c-4fe4-b4f6-e2a9e1377596)

**Comment by royc01** [comment]
这是什么浏览器

**Comment by heartacker** [comment]
edge 浏览器

**Comment by heartacker** [comment]
用 edge 打开 siyuan 网页版 ，安装 为 PWA

**Comment by royc01** [comment]
知识盲区，看看有没有其他大佬可以实现，抱歉了。
