### ISSUE TITLE
错误的标签层叠关系

### ISSUE THREAD

**Issue by JHPZ** [royc01/notion-theme#384]
![image](https://github.com/user-attachments/assets/73721d2b-37e0-4968-8f66-fbaa20a85667)
版本5.1.1

**Comment by royc01** [comment]
![image](https://github.com/user-attachments/assets/7c98b9fe-c15c-4488-b391-6b5a2dfe726d)
我这边显示正常的

**Comment by JHPZ** [comment]
再试试两个页面切换看看，我刚创建的文档也是正常的，且换到别的文档一下再回来

**Comment by JHPZ** [comment]
说不定是siyuan的bug~
