### ISSUE TITLE
引述样式

### ISSUE THREAD

**Issue by emanjusaka** [royc01/notion-theme#385]
引述的样式怎么变成这个样子了，之前还挺好看的。
![image](https://github.com/user-attachments/assets/8d303f08-470c-4c18-b6db-8f4defb47bb2)

**Comment by MeikoPA** [comment]
引述样式不能更改了，没找到更改样式，但是列表的更改样式还可以更改。不着调lz是不是一样
![1734420438910](https://github.com/user-attachments/assets/ac822997-b021-427c-87df-c2593fd86e10)

**Comment by royc01** [comment]
1、引述块的结构样式暂跟默认一致，之前也是一致的。2、引述callout样式不再内置，可以使用集市里的callout插件，就是我之前主题的样式了。
