### ISSUE TITLE
视图转换为导图后，页面的拖拽很不合理

### ISSUE THREAD

**Issue by innocentleaves** [royc01/notion-theme#386]
视图转换为导图后，页面的拖拽很不合理。
希望改成左键选择，右键拖拽

**Comment by royc01** [comment]
没理解

**Comment by innocentleaves** [comment]
![image](https://github.com/user-attachments/assets/116293cb-9778-44b8-bce5-b330acb78a2d)
滚动条只在整个导图页面的最下面有，当导图很大时，上面的部分根本看不到滚动条，因此页面的左右移动就变得很困难，只能通过左键框选到页面的最左或最右侧，让其滑动到想要的位置，操作极其不方便
![image](https://github.com/user-attachments/assets/99f032e0-d306-4d48-a73d-5c720772800a)
希望可以做成右键拖拽的形式，在导图的任何位置都能方便地进行左右移动

**Comment by royc01** [comment]
这视图的实质其实是列表，所以shift+滚轮顶顶，要加拖拽效果可能会有性能问题，后面再研究

**Comment by innocentleaves** [comment]
感谢大佬，我才知道shift+滚轮可以左右移动，这样也行，解决了我一直以来的苦恼，非常感谢！！！

**Comment by royc01** [comment]
![2](https://github.com/user-attachments/assets/2bb96f56-a796-4993-82be-f2dec5e6565d)
应该是这种效果吧？不知道有什么隐患先记录一下。

**Comment by innocentleaves** [comment]
对的对的

**Comment by royc01** [comment]
新版本v5.1.2已经支持

**Comment by innocentleaves** [comment]
非常感谢！！！
没想到我提的建议真的被采纳了，开心😊☺️😍
