### ISSUE TITLE
侧栏展开，低栏不应该被挤压

### ISSUE THREAD

**Issue by heartacker** [royc01/notion-theme#388]
![Screenshot_20241221-213809.png](https://github.com/user-attachments/assets/6cf6798b-b76b-413e-9ed1-610583bd5ccb)

方框部分

**Comment by royc01** [comment]
没看明白，为啥界面这么大，如果是移动端的话，暂时还没适配

**Comment by heartacker** [comment]
就是点开大纲的时候，它就会有个大大的空白
这个应该是电脑端，浏览器端，手机端都会有这样的问题

**Comment by heartacker** [comment]
不知道你这边是否可以试试呢？

**Comment by royc01** [comment]
![image](https://github.com/user-attachments/assets/43bb8891-3108-49f7-a46c-d89ea337443d)
我这边是正常的，是否有安装什么插件？或者我适配一下

**Comment by heartacker** [comment]
我看你这个图片也不对，这个底栏不应该靠底靠右吗？怎么是靠左的？底部状态栏应该是所有的最低，不应该在侧栏的左边

**Comment by royc01** [comment]
改了方案，因为之前要适配侧栏遮挡的问题，现在底栏直接挪到编辑器里面，这样就不会遮挡

**Comment by heartacker** [comment]
好吧，谢谢解答

还是希望，如果可以，还是应该放在他应该出现的地方，不然每次点击，这个都会移动，很干扰用户

**Comment by royc01** [comment]
现在底栏在编辑区域的方案我觉得挺好，可能你习惯了之前的方案吧，不过你那边还是显示还是有遮挡的问题，如果能提供其他信息我就好适配

**Comment by royc01** [comment]
没有更多信息先关闭了，感谢反馈
