### ISSUE TITLE
来一个墨水屏配色

### ISSUE THREAD

**Issue by heartacker** [royc01/notion-theme#389]
高对比度
墨水屏

**Comment by heartacker** [comment]
非常喜欢你的布局等，但是墨水屏需要纯色的，白色的。显示才清晰

**Comment by royc01** [comment]
抱歉，我手上暂时没有这样的设备，先不做了，感谢支持

**Comment by heartacker** [comment]
非常感谢，不过我还是强烈恳求能否帮忙做一个背景色是纯白色的。现在的所有的背景色都是米黄、粉红之类的，有点这种颜色在那个墨水瓶上面看的其实就不是清晰。
我只要纯白色的就行

**Comment by royc01** [comment]
默认明亮配色和forest配色就是编辑器纯白背景的
