### ISSUE TITLE
暗黑模式下加粗很不明显

### ISSUE THREAD

**Issue by baixiang-main** [royc01/notion-theme#39]
在dark模式下加粗效果几乎看不出，不知道能不能更换下样式

**Comment by royc01** [comment]
我觉着字体加粗就差不多这样效果了，与官方主题、第三方主题效果没差别，如果要特别区分建议添加字体颜色。

**Comment by baixiang-main** [comment]
> 我觉着字体加粗就差不多这样效果了，与官方主题、第三方主题效果没差别，如果要特别区分建议添加字体颜色。
得到回复，去仔细研究了一下，字体效果本身确实还是差不多的（也不知道是不是心理暗示的缘故），目前看起来有可能是与背景的颜色对比度上相对低一些，加粗之后感官就不强了。

**Comment by royc01** [comment]
主要是在黑色背景下，白色字体自带加粗错觉，所以看起来差别不大，换其他颜色区别就大了
