### ISSUE TITLE
使用主题，切换旧文章时出现：鼠标在客户端内移动，引入部分页面会变花白

### ISSUE THREAD

**Issue by code-lixm** [royc01/notion-theme#390]
1. 客户端版本：v3.1.17
2. 插件版本：v5.1.5
3. 电脑：MBP M4
使用其他主题（asri，官方）没有出现该问题，控制台没有报错。
触发场景：渲染正常的页面，alt+p切换到一个不经常打开，内容比较多的页面

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5363ddd3-2ac0-44b1-ae9e-deca44a8124c" />

**Comment by royc01** [comment]
白的是完全看不到么？还是等一下就有？如果一直存在，或者看看白的部分是哪个dom

**Comment by code-lixm** [comment]
> 白的是完全看不到么？还是等一下就有？如果一直存在，或者看看白的部分是哪个dom



> 白的是完全看不到么？还是等一下就有？如果一直存在，或者看看白的部分是哪个dom

两种情况都存在：
1. 白的是完全看不到：鼠标移入的地方就会变白，没有固定规则就像显卡渲染卡了一样
2. 等一下就有：快速滚动左侧文档树，就会出现变白，再出现

**Comment by royc01** [comment]
这个比较玄学，优化无从下手了

**Comment by royc01** [comment]
v5.1.6版本优化了一个卡顿的问题，等集市更新了可以再试试看，先关闭了
