### ISSUE TITLE
左右分屏后滚动条会在最上层

### ISSUE THREAD

**Issue by winter60** [royc01/notion-theme#41]
编辑时情况
![image](https://user-images.githubusercontent.com/23653326/196256924-d5362a5e-ae22-41f7-8db8-828cc091c53c.png)

设置窗口
![image](https://user-images.githubusercontent.com/23653326/196256995-584bc5e4-49f8-4f8a-9306-efb3699bef9a.png)

右侧alt+y后
![image](https://user-images.githubusercontent.com/23653326/196257067-ef0bd239-0567-4831-b3a2-d4a102de767e.png)

**Comment by royc01** [comment]
这个已经修复了，还没更新上去
