### ISSUE TITLE
是否考虑为标题增加序号标识

### ISSUE THREAD

**Issue by pokerLL** [royc01/notion-theme#42]
dark+集市主题图上就有 ，例如0.1 1.1 1.1.1这样子 
如果能有个功能直接改变文本在文本中添加这样的文字 而不仅仅展示的时候看到就好了

**Comment by royc01** [comment]
这个功能会受动态加载影响，不是很优雅，我考虑考虑

**Comment by PowerDi** [comment]
> 这个功能会受动态加载影响，不是很优雅，我考虑考虑
现有的标题级别标识，导出pdf的时候，会带有标题名字后面的几个点

**Comment by dsfdfsfds** [comment]
这个感觉序号不是很准，有时候需要滑到某章，序号才会编上

**Comment by howards-wang** [comment]
确实是的，习惯了有序号的标题，这样看笔记更有逻辑思路，希望作者能够增加一个这样的功能！谢谢

**Comment by royc01** [comment]
插件实现
