### ISSUE TITLE
siyuan2.4.1 版本和notion主题样式冲突问题

### ISSUE THREAD

**Issue by zburu** [royc01/notion-theme#43]
刚更新完客户端，由于客户端默认样式变动，导致使用notion主题时，样式有冲突。

---

1. 顶部：如果不设置顶栏隐藏，默认会有一大片空白，hover 的时候高度会闪烁。
![image](https://user-images.githubusercontent.com/65840178/196606124-984b30dd-eeb2-4fc0-9f55-360230aaf2ff.png)

---
 2. 底部状态栏
![image](https://user-images.githubusercontent.com/65840178/196606184-c27f4788-0cde-4647-811f-ab59ebb0cf19.png)

---

除此之外，其他问题暂未发现，希望作者可以更新以下主题。

**Comment by royc01** [comment]
请更新主题

**Comment by zburu** [comment]
刚发现主题没更新，打扰了
