### ISSUE TITLE
暗黑模式下代码块语法高亮主题 显示不正常

### ISSUE THREAD

**Issue by yxy823** [royc01/notion-theme#44]
这是a11y-dark主题 在notion-theme的显示效果
![image](https://user-images.githubusercontent.com/38773494/196682739-e4ff0eb5-41b6-4a03-88b1-7c9025e87974.png)

这是a11y-dark主题 在Dark+的显示效果
![image](https://user-images.githubusercontent.com/38773494/196682923-b5f4059e-2258-49be-9f26-a1c78465f4a7.png)

**Comment by royc01** [comment]
外观模式切换到暗黑，然后暗黑主题选择notion即可，直接按钮切换有点问题
