### ISSUE TITLE
代码块主题的字体颜色太暗了？

### ISSUE THREAD

**Issue by winter60** [royc01/notion-theme#46]
大佬，您看下是不是呀
![image](https://user-images.githubusercontent.com/23653326/196757087-51a1285e-e5a4-4726-9d18-87b3cfaf478c.png)

![image](https://user-images.githubusercontent.com/23653326/196757108-8d8bb63d-e2ff-45e5-ab84-f99d3ea98114.png)

主要是暗黑notion-dark，如果你的是正常的话，可能就是我自定义了颜色的问题。

**Comment by royc01** [comment]
外观模式切换到暗黑，然后暗黑主题选择notion

**Comment by royc01** [comment]
下个版本我把顶栏的dark按钮去掉吧，直接用外观模式转换
