### ISSUE TITLE
在块有命名或别名的情况下，块引用标识漂移

### ISSUE THREAD

**Issue by stonecutter-21** [royc01/notion-theme#47]
当块有命名或者别名的情况下，块引用标识的位置会与命名或别名左对齐，有可能遮挡正文。
<img width="1048" alt="截屏2022-10-21 11 19 52" src="https://user-images.githubusercontent.com/72546433/197103713-c8b9f9c4-f205-47c9-acbe-d758fab28c38.png">

复现步骤
（1）在无序列表中编辑正文
（2）给该列表块（不仅仅是子块，是整个列表容器块）命名
（3）引用整个列表块
好像默认主题没有这个问题
<img width="1039" alt="截屏2022-10-21 11 21 17" src="https://user-images.githubusercontent.com/72546433/197103931-7bc86a92-2873-4ce7-92d7-7dc4d880948b.png">

**Comment by royc01** [comment]
收到，感谢反馈
