### ISSUE TITLE
代码块对~=显示的建议

### ISSUE THREAD

**Issue by IrregularHunterZero** [royc01/notion-theme#48]
在MATLAB中不等运算是“~=”，但是使用notion-theme中的代码块，会自动显示为≈。如下：
![notion-theme](https://user-images.githubusercontent.com/116334892/197123305-462495b6-3ed0-4f7b-8e02-720dae47ff6d.png)

**Comment by royc01** [comment]
官方是这样显示呢，建议反馈到思源https://github.com/siyuan-note/siyuan/issues
