### ISSUE TITLE
右侧面板悬浮功能异常

### ISSUE THREAD

**Issue by yexsi** [royc01/notion-theme#50]
软件版本：MAC ARM 64 2.4.4
主题版本：2.6.5
问题描述：窗口显示或最大化显示时，右侧面板悬浮功能异常
问题复现：
1️⃣未点击**右侧面板悬浮**时，界面显示正常
<img width="1920" alt="问题截图1" src="https://user-images.githubusercontent.com/63133923/197395842-5999bad9-09a9-4fb4-8c1d-a89716be4f11.png">
2️⃣点击**右侧面板悬浮**后，右侧面板并未悬浮，且出现了布局异常的情况。底部出现滚动条，编辑区变为可横向滚动。
<img width="1920" alt="问题截图2" src="https://user-images.githubusercontent.com/63133923/197395876-2eada6bf-f9c5-4bde-b69c-2af83f394131.png">
<img width="1920" alt="问题截图3" src="https://user-images.githubusercontent.com/63133923/197395893-9b4cd97d-da10-442c-a5df-28437a366431.png">
3️⃣再次点击关闭**右侧面板悬浮**后，界面恢复正常
<img width="1920" alt="问题截图1" src="https://user-images.githubusercontent.com/63133923/197395842-5999bad9-09a9-4fb4-8c1d-a89716be4f11.png">

**Comment by royc01** [comment]
我这边是正常的，看看有没有其他小伙伴反馈

**Comment by yexsi** [comment]
谢谢作者，在集市中删除主题再重新安装主题，还是会出现同样的问题。目前应该是没救了

**Comment by royc01** [comment]
侧栏反链点出来还会偏移么

**Comment by yexsi** [comment]
软件版本更新到MAC ARM 2.5.5，把面板点出来后，还是同样的问题
<img width="1920" alt="存在问题4" src="https://user-images.githubusercontent.com/63133923/197399005-5955c323-b54e-456e-8154-442c5be235e9.png">

**Comment by royc01** [comment]
呃。。。还是看看其他人会不会出现

**Comment by yexsi** [comment]
在Win端、Mac端、Docker端部署最新版本软件及最新主题版本，仍存在上述问题。😭😭😭

**Comment by royc01** [comment]
重置一下外观试试

**Comment by yexsi** [comment]
使用恢复默认窗口功能后，再次点击右侧面板悬浮功能后，还是会复现上述问题😭

**Comment by royc01** [comment]
那真的不知道啥原因了，再看看其他人会不会出现这个问题。。不好定位

**Comment by yexsi** [comment]
嗯嗯感谢作者🧡

**Comment by yexsi** [comment]
> Mac端、Docker端部署最新版本软件及最新主题版本，仍存在上述问题。😭😭😭

补正：Win端右侧面板悬浮是没问题的，还请作者排查一下下，谢谢！

**Comment by yexsi** [comment]
补正：Win端右侧面板悬浮是没问题的，其他端仍旧存在问题。还请作者排查一下下，谢谢！

**Comment by royc01** [comment]
我应该能复现了，我再修修看
