### ISSUE TITLE
自动隐藏引起的几个错误

### ISSUE THREAD

**Issue by Nauh521** [royc01/notion-theme#51]
要先夸下新特性：**把左右悬浮面板按钮移到编辑器中部**。功能按钮应该靠近功能区域，这种折叠方式特别符合使用逻辑👍👍👍
然后反馈几个错误：
1. 顶栏自动隐藏状态下`历史记录`窗口错位。鼠标移开顶栏后，窗口会一起消失。
![演示1](https://user-images.githubusercontent.com/112914211/197399910-9706189b-5881-4666-af11-65e17d119a06.gif)
2. 顶栏固定状态下会遮挡全屏关系图按钮
![演示2](https://user-images.githubusercontent.com/112914211/197400365-eab112e8-c51d-4a99-bd50-44c3e2a8895c.gif)
3. 右侧栏自动隐藏状态下遮挡编辑窗口滚动条
![演示3](https://user-images.githubusercontent.com/112914211/197400556-47a00dff-dad4-446f-93e9-b7996640fc42.gif)
---
上述错误不影响`notion-theme`的使用，大佬请酌情优化。
最后，非常感谢大佬抽出时间为我们这帮白瓢怪带来这么好用的主题💖💖💖

**Comment by royc01** [comment]
感谢反馈，下个版本修复
