### ISSUE TITLE
【最近打开文档】不推荐使用第一个版本，第二个版本可能更合适；

### ISSUE THREAD

**Issue by BryceAndJuly** [royc01/notion-theme#52]
第二个版本添加了——支持删除指定历史条目的小特性，在使用上更接近于浏览器的历史记录，感觉会更友好一些。

另外有个小建议就是，日历面板其实有刷新按钮（日历右上角的多少日），建议修改一下【主题特性】列表下的一项：

> 日历面板 | 主题界面左上角【日历】按钮开启，新建日记后，重启思源才能显示

其实不用重启也行，日历刷新一两次后一般就能检测到新创建的日记。

**Comment by royc01** [comment]
感谢提醒，下个版本优化

**Comment by royc01** [comment]
> 第二个版本添加了——支持删除指定历史条目的小特性，在使用上更接近于浏览器的历史记录，感觉会更友好一些。
> 
> 另外有个小建议就是，日历面板其实有刷新按钮（日历右上角的多少日），建议修改一下【主题特性】列表下的一项：
> 
> > 日历面板 | 主题界面左上角【日历】按钮开启，新建日记后，重启思源才能显示
> 
> 其实不用重启也行，日历刷新一两次后一般就能检测到新创建的日记。

现在新建日记点两下会建重名日记，可以规避么？还是只能先点刷新？

**Comment by BryceAndJuly** [comment]
现在是要先刷新的。规避的话，在它新建完笔记之后，让它自动刷新一下日历或许可以。我到时候试试。

**Comment by royc01** [comment]
了解，感谢大佬的功能

**Comment by BryceAndJuly** [comment]
自动刷新的话，刚刚试了一下，有点用，你有空可以试试在那个`日历/js/app.js`，
搜索

```shell
(a,window.parent._t,!0)},500))}}}
```

替换成有延时刷新的：

```shell
(a,window.parent._t,!0)},500));setTimeout(()=>{window.location.reload(true)},2000);}}}
```
看看效果；

**Comment by BryceAndJuly** [comment]
对了，那个【最近打开文档】的功能，如果在新版本检测不到页签变动的话，你可以试试改一下它的选择器，就是
搜索

```shell
"div[data-type='wnd'] > div.fn__flex ul.fn__flex.layout-tab-bar.fn__flex-1"
```

应该能搜到两个结果，

替换成

```shell
"div[data-type='wnd'] > div.fn__flex ul.fn__flex.layout-tab-bar"
```

然后再看看效果。

**Comment by royc01** [comment]
好的，感谢大佬

**Comment by BryceAndJuly** [comment]
我今天看了下创建文档后刷新标记的问题，一开始的自动延时刷新的方法实在是多此一举，刚创建的文档肯定在，不需要再去查询判断是否存在再标记。在创建完文档后处理链接并将日期加入标记就可以了。可以试一下第7个版本。

**Comment by royc01** [comment]
> 我今天看了下创建文档后刷新标记的问题，一开始的自动延时刷新的方法实在是多此一举，刚创建的文档肯定在，不需要再去查询判断是否存在再标记。在创建完文档后处理链接并将日期加入标记就可以了。可以试一下第7个版本。

感谢，下个版本更上去😘
