### ISSUE TITLE
无序列表折叠样式的若干问题

### ISSUE THREAD

**Issue by stonecutter-21** [royc01/notion-theme#53]
（1）无序列表标题折叠后，省略号样式会覆盖标题层级的样式
<img width="298" alt="截屏2022-10-26 16 34 04" src="https://user-images.githubusercontent.com/72546433/197976527-e842e924-0652-4bc3-ad92-79434b649404.png">
（2）若该列表项以数学公式结尾，折叠后省略号样式会自动换行
<img width="275" alt="截屏2022-10-26 16 35 19" src="https://user-images.githubusercontent.com/72546433/197976827-f2367aa7-6a06-4001-8fe6-40f03ba9132f.png">

**Comment by royc01** [comment]
1、这个只能二选一，伪类只能有一项，所以选择了省略号
2、这个问题下个版本调一下看看

**Comment by stonecutter-21** [comment]
大佬，貌似在标题中仍然会存在省略号换行的现象。只要文本+数学公式并以数学公式结尾应该就会

<img width="395" alt="截屏2022-10-28 16 06 17" src="https://user-images.githubusercontent.com/72546433/198537110-8de7ca3e-5155-4637-9d7d-d3784ed26e1f.png">

**Comment by royc01** [comment]
😅好吧，我再调调
