### ISSUE TITLE
右侧面板悬浮功能遮挡PDF更多菜单

### ISSUE THREAD

**Issue by EberhardLin** [royc01/notion-theme#54]
![image](https://user-images.githubusercontent.com/98400319/198073754-9f175f24-8b15-43a0-a132-84f1dea57aaa.png)

**Comment by Oltermare** [comment]
也会遮挡标签界面的刷新按钮，在分屏查看非普通文档界面的时候容易出问题
![image](https://user-images.githubusercontent.com/64324088/198079365-db910440-ee06-4baa-9dd8-67be93334a9f.png)

**Comment by royc01** [comment]
感谢反馈，下个版本修复
