### ISSUE TITLE
自定义日记格式，日历面板不显示且无法跳转

### ISSUE THREAD

**Issue by HowcanoeWang** [royc01/notion-theme#55]
![image](https://user-images.githubusercontent.com/19968935/198158890-decfd5da-cdf6-424c-ab80-0b7b4f183cf3.png)

![image](https://user-images.githubusercontent.com/19968935/198158917-abd2ebed-f2b2-4dbf-abbe-aafcd68f18f6.png)

![image](https://user-images.githubusercontent.com/19968935/198158966-d56bf7be-6b75-4056-947c-b8bc44c206a4.png)

**Comment by royc01** [comment]
仅显示2022-10-27这种格式的文档标题

**Comment by HowcanoeWang** [comment]
> 仅显示2022-10-27这种格式的文档标题

https://github.com/royc01/notion-theme/blob/d8091cbb4edd2f291b6a93388b4d52fe0c891571/calendar/js/app.987de072.js#L1

要不提交一份可读性的代码，我自己来魔改看看

**Comment by royc01** [comment]
我也是从社区里面拿的，可以参考https://ld246.com/article/1662969146166

**Comment by HowcanoeWang** [comment]
> 我也是从社区里面拿的，可以参考https://ld246.com/article/1662969146166

救命，这完全是加密过后的js，变量名全是单个字母真的有毒(￣_￣|||)

```javascript
(function (t) {
    function e(e) {
        for (var a, i, s = e[0], c = e[1], l = e[2], u = 0, h = []; u < s.length; u++) (i = s[u]), Object.prototype.hasOwnProperty.call(n, i) && n[i] && h.push(n[i][0]), (n[i] = 0);
        for (a in c) Object.prototype.hasOwnProperty.call(c, a) && (t[a] = c[a]);
        d && d(e);
        while (h.length) h.shift()();
        return r.push.apply(r, l || []), o();
    }
    function o() {
        for (var t, e = 0; e < r.length; e++) {
            for (var o = r[e], a = !0, s = 1; s < o.length; s++) {
                var c = o[s];
                0 !== n[c] && (a = !1);
            }
            a && (r.splice(e--, 1), (t = i((i.s = o[0]))));
        }
        return t;
    }
    var a = {},
        n = { app: 0 },
        r = [];
    function i(e) {
        if (a[e]) return a[e].exports;
        var o = (a[e] = { i: e, l: !1, exports: {} });
        return t[e].call(o.exports, o, o.exports, i), (o.l = !0), o.exports;
    }
```

**Comment by HowcanoeWang** [comment]
成功定位到获取日历模板字符串了

![image](https://user-images.githubusercontent.com/19968935/198258257-7fd42685-8bf6-4df8-b1ba-1474664216ab.png)

然后就是解析这个字符串，替换掉那些硬编码的地方了

> 这个你大概没有看压缩包下方的文字说明。日记路径目前是固定的，并没有读取设置。
>
> 不过要改成你现在用的这种也不难，打开 工作空间\data\widgets\日历\js\app.796dd5e3.js
> 
> 搜索
> 
> /daily note/
> 替换成
> 
> /

以及模板的日期字符串替换：

> ![image](https://user-images.githubusercontent.com/19968935/198258643-ec9980be-415c-49d0-a606-f971c2bbfa89.png)

**Comment by royc01** [comment]
这个没关系了，自己能用就好

**Comment by HowcanoeWang** [comment]
> 这个没关系了，自己能用就好

我已经改好了，自动读取当前笔记本的今日速记模板变量，然后把硬编码的路径全部替换了，现在完全兼容所有的今日速记路径

![image](https://user-images.githubusercontent.com/19968935/198294687-60c18da8-e5e1-45e4-9211-2bcf9157dc28.png)
