### ISSUE TITLE
[提议] 正文使用两侧对齐

### ISSUE THREAD

**Issue by choyy** [royc01/notion-theme#58]
这应该可以用主题实现吧？
![图片](https://user-images.githubusercontent.com/68107073/198820063-8ef5139e-aeba-41f5-88d7-79a1a1f93b39.png)
**两侧对齐比默认好看多了：**
**这是默认**：
![图片](https://user-images.githubusercontent.com/68107073/198820077-bcd1230e-bde4-46d7-b25d-4441739d10e6.png)
**这是两侧对齐**：
![图片](https://user-images.githubusercontent.com/68107073/198820099-ff091b07-af6a-489e-b1fc-2f22911259d9.png)

**Comment by royc01** [comment]
这个应该不做默认实现，可以在设置-外观-代码片段，添加以下css片段
```
.protyle-wysiwyg [data-node-id] [spellcheck=false]{
text-align: justify;}
```
