### ISSUE TITLE
2.7.0平板端打开链接后界面整体上移

### ISSUE THREAD

**Issue by Workaholic2142** [royc01/notion-theme#60]
只有点开链接块会出现，界面上移将近1/5，底部出现相应的空白，顶端任务栏上移到界面之外以至于无法操作。通过竖屏翻转再横屏可以暂时解决。
	如果链接块的对象是文章的第一行内容则不会出现这种情况（如果第一行是无序列表的话仍然会上移），打开的是引用快也不会如此。只有链接的对象是一篇文章中间开始的内容时会出现界面上移。
	设备：华为matepad11，笔记版本2.4.7

截图1：鼠标移动至链接块时情况正常。
![Screenshot_20221030_081212_org b3log siyuan](https://user-images.githubusercontent.com/116984684/198857160-516f80f8-68c9-4e89-a5e2-b4a5f3b6b18c.jpg)
截图2：点击进入后进入出现界面上移，竖屏再横屏可以暂时解决。
![Screenshot_20221030_081152_org b3log siyuan](https://user-images.githubusercontent.com/116984684/198857163-137d0c67-b0bb-4e0e-bf9e-eede8bbbf254.jpg)

**Comment by royc01** [comment]
抱歉，我这边没有平板设备，其他端有这样的问题么？

**Comment by Workaholic2142** [comment]
> 抱歉，我这边没有平板设备，其他端有这样的问题么？

pc端没有问题，手机端更新比较麻烦所以没更新。平板竖屏操作是没有问题的，只有横屏会出现，比较奇怪。

**Comment by Workaholic2142** [comment]
> 抱歉，我这边没有平板设备，其他端有这样的问题么？

pc端没有问题，手机端更新比较麻烦所以没更新。平板竖屏操作是没有问题的，只有横屏会出现，比较奇怪。

**Comment by royc01** [comment]
啊。。这。。。就很难定位了
