### ISSUE TITLE
思源笔记2.4.8支持PDF明亮和暗黑模式切换，notion-theme暗黑模式下无法实现切换到明亮模式

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#64]
思源笔记2.4.8支持PDF明亮和暗黑模式切换，notion-theme暗黑模式下PDF无法实现切换到明亮模式。
经测试：notion-theme明亮模式下可以切换PDF显示模式。

**Comment by royc01** [comment]
感谢反馈，下个版本修复
