### ISSUE TITLE
左侧面板隐藏按钮会覆盖面包屑和PDF工具栏

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#66]
**左侧面板隐藏**按钮会覆盖面包屑和PDF工具栏，尤其是PDF工具栏，无法点击到工具栏的切换侧栏按钮。

**Comment by royc01** [comment]
可以截图看看么

**Comment by GentooXu** [comment]
![image](https://user-images.githubusercontent.com/39244046/198969223-d4586d5b-3374-4c1d-8567-82fd7686c422.png)


> 可以截图看看么

**Comment by royc01** [comment]
好吧。。我一般都放右边用。。面包屑应该挡不住吧

**Comment by GentooXu** [comment]
> 好吧。。我一般都放右边用。。面包屑应该挡不住吧

![image](https://user-images.githubusercontent.com/39244046/198971403-2b7b5fc7-9f6c-4ec8-86b7-5779e65bc347.png)

会将文档面包屑覆盖了。

**Comment by royc01** [comment]
设置-外观-恢复默认    试试看

**Comment by GentooXu** [comment]
> 设置-外观-恢复默认 试试看

恢复模式之后显示正常了，谢谢！！
没搞明白这个什么原因！

**Comment by GentooXu** [comment]
> 好吧。。我一般都放右边用。。面包屑应该挡不住吧

恢复默认后PDF工具栏也正常了。

**Comment by GentooXu** [comment]
不对，PDF工具栏覆盖的还是有问题，是我自己修改了CSS才正常的。

**Comment by royc01** [comment]
pdf是还没适配，面包屑应该好了
