### ISSUE TITLE
无图标文件钉住后会将面包屑向下挤压，造成面包屑和左（右）侧面板悬浮按钮错位。

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#68]
![image](https://user-images.githubusercontent.com/39244046/198976810-2be063b1-b822-4d40-99ff-12b4ca1e84c3.png)
![image](https://user-images.githubusercontent.com/39244046/198976881-fefb61c3-36ec-46ca-b7ec-7c6328b1e066.png)
抱歉大神，我很喜欢这款主题，但是有点强迫症，请见谅哈。

**Comment by royc01** [comment]
了解
