### ISSUE TITLE
能否加上鼠标中键单击，在新页面打开

### ISSUE THREAD

**Issue by dsfdfsfds** [royc01/notion-theme#69]
类似浏览器的逻辑，中键单击可以在新页面打开大纲、双链等。

**Comment by royc01** [comment]
不太理解你的意思，现在点击文档树和锚文本不是新页面打开吗

**Comment by dsfdfsfds** [comment]
是滚轮单击，在浏览器单击是在新标签页打开网页。dark主题也可以实现类似操作，滚轮单击会再生成一个页面，方便同时查看其他内容。包括锚文本、大纲、文档树。尤其是大纲这个，同时看前后的内容比较方便。
![image](https://user-images.githubusercontent.com/117132841/199233238-917ad584-6c10-49d4-85d7-ff4aa7530d92.png)

**Comment by royc01** [comment]
明白了，我看能不能加上

**Comment by dsfdfsfds** [comment]
您好，关于新功能，一个是在大纲点击无法跳转到大纲对应的正文位置，打开后仍为现在文档的位置。二是目前跳转到对应位置的快捷键是 ctrl + alt + 中键，但是这个功能可能比只打开一个原位置的新窗口更常用，建议能够简化需要按的键盘数量。三是app目前打开pc模式窗口比较慢，如果只是为了对照来看，app模式效率更高。能否把快捷键设置的更方便。鼠标右键+中键有点费劲，或者跟 alt + 中建交换一下

**Comment by royc01** [comment]
这个跟中键折叠冲突，操作逻辑跟HBX主题一致
