### ISSUE TITLE
引述块反馈

### ISSUE THREAD

**Issue by UFDXD** [royc01/notion-theme#7]
![image](https://user-images.githubusercontent.com/97731736/158982196-060f78dd-234b-4b03-9ad8-082722be6863.png)

以上是目前已经修复的样子，但是黑色的竖线被包括进去了

![image](https://user-images.githubusercontent.com/97731736/158982677-6071629d-78fa-4773-9f45-3fe6674e9a45.png)
这是未更新前版本的样子，它们并不相同，我更喜欢原来的样子，请再改动一下（另外这次列表的改动很赞！）

**Comment by UFDXD** [comment]
![2022-03-18_181105](https://user-images.githubusercontent.com/97731736/158984333-3afa362d-3ea4-4746-856e-e0fd4e3fd8a6.jpg)
这是最新修复的我的自定义模板排版（黑色的竖线在引述块内）

![2022-03-18_180656](https://user-images.githubusercontent.com/97731736/158984307-862a60b3-65fc-46e7-bc21-62152d204a82.jpg)
这是未更新前的我的自定义模板排版（黑着的竖线遮挡引述块左边框）

很显然未更新前的引述看上去风格更好一些。

**Comment by royc01** [comment]
更回去了，改了点细节
