### ISSUE TITLE
左侧悬浮按钮和文档面包屑图标重合，无法点击文档面包屑

### ISSUE THREAD

**Issue by XinLi0111** [royc01/notion-theme#70]
![image](https://user-images.githubusercontent.com/31495943/199171969-8d1c0aee-d651-492c-8aa9-2a7c3d5329ba.png)
请求大佬帮助！
尝试过更换主题再换回来。禁用了网络缓存，重新 ctrl F5 刷新，均没有解决问题。2.7.1更新后出现的，更新了2.7.2也有问题。思源版本2.4.8

**Comment by royc01** [comment]
请尝试  设置-外观-恢复默认

**Comment by XinLi0111** [comment]
回复太快了，有用，感谢感谢！
