### ISSUE TITLE
关闭按钮在边缘不可点击

### ISSUE THREAD

**Issue by cuicui-V5** [royc01/notion-theme#71]
最大化窗口想要关闭软件时, 把光标移到右上角之后还要微调位置, 这样体验就较差...
![Snipaste_2022-11-02_09-23-39](https://user-images.githubusercontent.com/60726697/199372746-8e486223-f53c-4a85-b36a-07f643f65874.png)

**Comment by royc01** [comment]
感谢反馈，下个版本改进

**Comment by cuicui-V5** [comment]
> 感谢反馈，下个版本改进

感谢作者的项目, 这款主题个人认为是市场里面看起来最舒服的👍

**Comment by royc01** [comment]
谢谢支持
