### ISSUE TITLE
整体界面布局错位

### ISSUE THREAD

**Issue by yxy823** [royc01/notion-theme#72]
红色框部分是莫名奇妙多出来的，绿色框部分本来应该显示的文档标题、同步等工具按钮消失了，是整体向上移动了。
一个已知的触发操作：在大纲栏点击标题进行跳转，多点几次就出现了

主题版本：2.7.2
思源笔记版本：2.4.9
![image](https://user-images.githubusercontent.com/38773494/199631275-45a4d547-7648-4459-97c6-39f26d7cdce5.png)
![image](https://user-images.githubusercontent.com/38773494/199631967-26d580a8-4ac9-4aea-90d0-ca2f57e51fb5.png)

**Comment by royc01** [comment]
是什么端的？

**Comment by royc01** [comment]
好的 ，我再看看

**Comment by royc01** [comment]
我这边复现不了，看能不能录个屏

**Comment by yxy823** [comment]
我下午重装了下思源笔记2.4.9可以了。。。

**Comment by yxy823** [comment]
我重装了思源2.4.9好了

**Comment by royc01** [comment]
没有错位了是吧？

**Comment by yxy823** [comment]
是的，现在可以了

**Comment by royc01** [comment]
好的，那我关闭了

**Comment by yxy823** [comment]
> 好的，那我关闭了

换了个文档又不行了。。。
![布局错位](https://user-images.githubusercontent.com/38773494/199662439-29a97831-97d3-47e7-ab72-3e9b857de88f.gif)

**Comment by yxy823** [comment]
> 好的，那我关闭了

换了Tsundoku Dark主题没有出现该问题
![其他主题](https://user-images.githubusercontent.com/38773494/199662958-3df9ad5d-8e80-41dc-82fe-12c8bdf1aa5a.gif)

**Comment by royc01** [comment]
方便的话文档发一份我看看？

**Comment by yxy823** [comment]
邮箱吗？

**Comment by yxy823** [comment]
[明朝.md](https://github.com/royc01/notion-theme/files/9926178/default.md)

**Comment by royc01** [comment]
[notion-theme.zip](https://github.com/royc01/notion-theme/files/9926287/notion-theme.zip)
麻烦帮忙测试一下，解压覆盖到主题文件夹即可

**Comment by yxy823** [comment]
好的，我去试一下

**Comment by yxy823** [comment]
可以了！

**Comment by royc01** [comment]
好的，应该是一个打开最近文档那个功能错位了，非常感谢
