### ISSUE TITLE
隐藏按钮后反向链接按钮向下移动，被右下角的隐藏停靠栏覆盖了

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#73]

**Comment by GentooXu** [comment]
![image](https://user-images.githubusercontent.com/39244046/199978582-921bebcf-f722-4e7f-9126-a51d040d56ee.png)
![image](https://user-images.githubusercontent.com/39244046/199978722-a67b2f98-ad25-465c-9621-54effa64defc.png)
![image](https://user-images.githubusercontent.com/39244046/199978764-1a27bb66-0d1d-46ec-b4ad-3ba7e5066d3b.png)

**Comment by GentooXu** [comment]
再加一个：隐藏按钮后再关闭左侧面板，标题栏左侧也会出现留白，麻烦您看一下能否优化一下，期待。
![image](https://user-images.githubusercontent.com/39244046/199979535-7528f842-69e0-4f23-a76c-512975316b3c.png)

**Comment by royc01** [comment]
了解..  新版各种翻车

**Comment by GentooXu** [comment]
> 了解.. 新版各种翻车

很不错了，大版本更新可以理解，小版本持续优化，支持您！
