### ISSUE TITLE
新窗口alt+中键功能

### ISSUE THREAD

**Issue by winter60** [royc01/notion-theme#77]
和Dark+查看与编辑源码触发方式冲突了，想禁用或修改怎么改呢？

**Comment by royc01** [comment]
![QQ截图20221105175311](https://user-images.githubusercontent.com/38906705/200113984-b467feb4-d017-4927-bb6f-895896d5144f.jpg)
js里面注释这一行

**Comment by winter60** [comment]
谢谢大佬，提个小建议，将各种功能改为可配置，放到缓存或放到配置文件中（好像可放snippets目录），不然每次更新都要改。

**Comment by royc01** [comment]
整合方便开箱即用，自定义配置的话普通用户比较麻烦

**Comment by winter60** [comment]
好的，我只是随便一提，看来我得每次都改了。

**Comment by royc01** [comment]
先注释掉，然后在代码片段引用呢

**Comment by winter60** [comment]
> 先注释掉，然后在代码片段引用呢

同样需要每次去主题中注释掉，如果不能配置的话，我只有去换dark+的快捷键了。

还好dark+提供了一个方法就是去改配置，https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/issues/102
不过得想另一套快捷键，有点伤脑筋。
