### ISSUE TITLE
左/右侧面板悬功能浮异常

### ISSUE THREAD

**Issue by yexsi** [royc01/notion-theme#78]
软件版本：Win 2.4.9
主题版本：3.0.0
问题描述：
1.左侧、右侧面板悬浮按钮在多次点击后，会改变按钮颜色，重置主题功能可解决。
![问题1 00_00_00-00_00_30](https://user-images.githubusercontent.com/63133923/200120387-e49f7865-a775-4c22-840d-389e96fa9d49.gif)

2.在不打开文档时，多次点击两侧面板悬浮功能后，按钮仍会变色；同时左侧面板变为悬浮状态后，点击重置主题，并不能恢复为默认状态，左侧面板仍为悬浮状态，需要手动点击取消悬浮。
![问题2 00_00_00-00_00_30](https://user-images.githubusercontent.com/63133923/200120754-15983712-a683-4340-896b-3a4e47da02e1.gif)

**Comment by royc01** [comment]
1、下个版本再测试看看
2、关闭侧栏的情况下不要打开悬浮
