### ISSUE TITLE
之前notion的那个暗色主题挺好看的，希望能整合一下

### ISSUE THREAD

**Issue by mingyong-g** [royc01/notion-theme#80]
## 大佬，之前notion的那个暗色主题挺好看的，希望能整合一下，
- 目前这个暗色主题，有点“黑的发亮“”的感觉，希望在新的版本中把之前的那个暗色主题也整合进去

**Comment by royc01** [comment]
暗黑主题选择Savor，然后主题模式选择暗黑模式

**Comment by mingyong-g** [comment]
✅ GET 原来啥都不选就是默认效果👍
