### ISSUE TITLE
新主题平板端打开笔记后顶部工具栏右侧按钮消失

### ISSUE THREAD

**Issue by Workaholic2142** [royc01/notion-theme#81]
如题，没打开笔记的时候工具栏正常，打开笔记后右侧按钮消失，按钮消失后用快捷键也无法呼出，比如Ctrl+P全局搜索没有用。改为垂直页签暂时解决，但竖屏的时候可显示面积又过小。

![Screenshot_20221106_164441_org b3log siyuan](https://user-images.githubusercontent.com/116984684/200162230-be88101b-9196-4151-9a71-1549bba4c85e.jpg)

**Comment by royc01** [comment]
设置-外观-恢复默认试试看，如果不行就等下个版本再试试看

**Comment by royc01** [comment]
新版正常的话这个就关闭了

**Comment by Workaholic2142** [comment]
> 

还是不行…只要存在页签右边就会没有按钮。

**Comment by royc01** [comment]
那下个版本再更新试试看，或者看看其他小伙伴有没有这样的情况，我这边复现不了
