### ISSUE TITLE
悬浮右侧边板后不显示面包屑了，无法进行相关的操作，比如复制等。

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#84]
![image](https://user-images.githubusercontent.com/39244046/200235820-a6fceac4-08d4-44ab-ace5-3c4825b2e791.png)
![image](https://user-images.githubusercontent.com/39244046/200235845-627d9d8f-2465-45a4-992d-496f2e5bd4ae.png)

**Comment by royc01** [comment]
悬浮块标无解，因为他跟侧栏动画冲突，之前已经尝试过
