### ISSUE TITLE
希望单独出个不带附加功能版本

### ISSUE THREAD

**Issue by Temacc0531** [royc01/notion-theme#85]
现在的版本功能有点多，导致主题变得有些重，日常使用起来上下滑动页面都有些卡顿

但是这个主题的样式又非常好看

所以斗胆提出这个需求，大佬能否出个只有外观而不带其他附加功能的纯享版

**Comment by royc01** [comment]
每版我都有测试过，应该不会有性能问题，你可以把主题下的theme.js删掉，再打开试试看。之前群里小伙伴不用我的主题也会卡顿的，外观恢复默认后就好了，你也可以试试看。

**Comment by Temacc0531** [comment]
尝试了好像没用，你可以试下在帮忙文档上下滚动，默认主题还是会丝滑一些，包括但不限于在文档创建日期在获取的时候就会很卡

**Comment by royc01** [comment]
我这边删了附加功能也没啥差别，或者你录个会卡顿的情况看看

**Comment by Temacc0531** [comment]
![GIF 22-11-10 12-02-35](https://user-images.githubusercontent.com/101307399/200999584-714b49cd-7baa-4373-a76c-230129450a21.gif)
![GIF 22-11-10 11-12-36](https://user-images.githubusercontent.com/101307399/200999595-e75490d9-dda1-4200-a10b-a046722365e2.gif)

录屏帧率有点低看不太出来，但是实际手感差别很大。主要是跳转打开文档到获取完文件创建日期这段时间

**Comment by royc01** [comment]
你试试把主题下的js删了会不会好一点，我这边获取文件时间也不会影响性能的
