### ISSUE TITLE
面板悬浮可以增加其他触发方式吗？

### ISSUE THREAD

**Issue by yxy823** [royc01/notion-theme#86]
鼠标悬浮容易误触发，鼠标从思源笔记界面离开的时候，总是会闪烁一下，能否像思源笔记引用块那样？增加额外的触发方式(例如，按下ctrl键 + 鼠标悬浮才触发)

**Comment by royc01** [comment]
感谢反馈，这个应该不会增加了，悬浮触发区域也做得很窄，应该很少误触，抱歉了
