### ISSUE TITLE
左上角图标显示左边空白，整体右移

### ISSUE THREAD

**Issue by Monokeros-zero** [royc01/notion-theme#88]
左上角图标显示左边空白，整体右移
![image](https://user-images.githubusercontent.com/54490916/200769134-58ec9e7a-30b7-45ae-8057-a63f73576add.png)

**Comment by royc01** [comment]
重新安装主题或者设置-外观-恢复默认  试试看

**Comment by Monokeros-zero** [comment]
> 

不行，原因好像是会员图标实际没有隐藏造成的，点击左侧空白可以打开会员界面

**Comment by Monokeros-zero** [comment]
> 重新安装主题或者设置-外观-恢复默认 试试看

不行，原因好像是会员图标实际没有隐藏造成的，点击左侧空白可以打开会员界面

**Comment by royc01** [comment]
会员图标是不隐藏的啊，然后文档树拉宽一点图标就全显示了

**Comment by Monokeros-zero** [comment]
> 会员图标是不隐藏的啊，然后文档树拉宽一点图标就全显示了

我一直是把顶栏显示vip关掉的，之前都没问题，更新savor版本后出的问题

**Comment by royc01** [comment]
那只能先空在那了，因为页签和顶栏合并，固定了宽度，后续再想想怎么修

**Comment by Monokeros-zero** [comment]
> 那只能先空在那了，因为页签和顶栏合并，固定了宽度，后续再想想怎么修

好的，期待后续更新
