### ISSUE TITLE
关于按钮重复出现及自定义属性刷新不生效的问题

### ISSUE THREAD

**Issue by Morganwan90** [royc01/notion-theme#9]
1. 比如，点击列表转换为表格后，按shift+click弹出属性框，再右键块，那个‘列表转换为表格’及‘列表恢复模式’就重复一直弹出。
2. 点击列表转换为表格后，虽然样式变了，但是好像属性框中显示还是没有，刷新后会恢复默认。

不懂JS....但是这个功能很好用吖~求教大佬

**Comment by royc01** [comment]
正想改呢，不需要了？

**Comment by Morganwan90** [comment]
> 正想改呢，不需要了？

白天的时候自己摸索了改了一下.... 那个1、改成mousup，setinterval改成settimeout后解决了...2、用API再设一次后解决了...
但是我不懂JS...我就是看着别的主题依样画葫芦整的，不知道会不会出其他bug.

**Comment by royc01** [comment]
那正好，我直接kiang你的来用，哈哈

**Comment by Morganwan90** [comment]
哈哈..好哒~~

royc01 ***@***.***> 于2022年4月22日周五 10:08写道：
