### ISSUE TITLE
vinegar主题日历看不到星期几

### ISSUE THREAD

**Issue by CFmeinz** [royc01/notion-theme#91]
![image](https://user-images.githubusercontent.com/117926795/201133162-0d9ef73a-2b40-4c98-abfa-a8194607d9e6.png)

**Comment by CFmeinz** [comment]
![image](https://user-images.githubusercontent.com/117926795/201138889-26977df4-c85d-4593-b34f-ffa502902d10.png)
github图标也看不到

**Comment by CFmeinz** [comment]
![Uploading image.png…]()
历史记录的字也看不到

**Comment by royc01** [comment]
感谢反馈
