### ISSUE TITLE
点击日历的某个日期添加的文档的位置能否修改 

### ISSUE THREAD

**Issue by CFmeinz** [royc01/notion-theme#92]
不是指放在哪个笔记本 
![image](https://user-images.githubusercontent.com/117926795/201135774-0d3b5135-eb52-464a-8d91-332d63d8e7c3.png)
我想把带日期的文档直接放在笔记本中 不嵌套上图这些

**Comment by royc01** [comment]
改变位置是右键笔记本-设置

**Comment by royc01** [comment]
但是文档名要保持2022-11-11这种格式

**Comment by royc01** [comment]
哦，那应该要手动改js了，`Savor\calendar\js\app.987de072.js`打开这个
`/daily note/${e[0]}/${e[1]}/${o}`这个字段改为`/${o}`

**Comment by CFmeinz** [comment]
感谢！已修改
