### ISSUE TITLE
悬浮页面下有序列表第三级第三个序号的“.”移到下一行

### ISSUE THREAD

**Issue by Workaholic2142** [royc01/notion-theme#94]
仅在引用上打开悬浮页面后出现，稳定触发。
![capture_20221111171001028(1)](https://user-images.githubusercontent.com/116984684/201306777-978bb718-0448-42b7-92d1-a467457f580b.jpg)

**Comment by royc01** [comment]
这个应该是字体问题，换默认试试？

**Comment by Workaholic2142** [comment]
> 这个应该是字体问题，换默认试试？

确实是字体问题，感谢！
