### ISSUE TITLE
日历中星期几错误

### ISSUE THREAD

**Issue by CFmeinz** [royc01/notion-theme#96]
![image](https://user-images.githubusercontent.com/117926795/201459357-c25e64fd-b155-4596-ae2f-4030ec940e38.png)

12号周六是对的 
日历中12号对应Fr是错的

**Comment by royc01** [comment]
感谢反馈，下个版本更新

**Comment by HappyJamesL** [comment]
![image](https://user-images.githubusercontent.com/12409317/215652286-2e206c5d-76f2-4f0d-956b-a68c158ebdd5.png)
日历显示星期几还没有修复?

**Comment by royc01** [comment]
> ![image](https://user-images.githubusercontent.com/12409317/215652286-2e206c5d-76f2-4f0d-956b-a68c158ebdd5.png) 日历显示星期几还没有修复?

新版可能把bug又给弄回去了，下个版本修复

**Comment by HowcanoeWang** [comment]
已在这次发布中修复：https://github.com/HowcanoeWang/calendar/releases/tag/230201
