### ISSUE TITLE
siyuan v2.4.12搜索不到该主题

### ISSUE THREAD

**Issue by DaYangtuo247** [royc01/notion-theme#97]
![image](https://user-images.githubusercontent.com/73392515/201507818-15d08b06-c325-456e-9fbe-5f8c824de48e.png)

![image](https://user-images.githubusercontent.com/73392515/201507823-58d20823-1f8e-440f-96cc-b9ed3d329732.png)

**Comment by royc01** [comment]
已经更名为Savor，只是仓库还没改
