### ISSUE TITLE
页面边距未自适应

### ISSUE THREAD

**Issue by GentooXu** [royc01/notion-theme#98]
操作步骤如下：

1. 在Windows下，不隐藏左侧面板，`Win + →`将思源笔记放到右侧1/2屏。
![image](https://user-images.githubusercontent.com/39244046/201510746-46b29b04-bba5-4382-b938-972d9e4449c1.png)
2. 隐藏左侧面板，此时，页面边距不会自适应。
![image](https://user-images.githubusercontent.com/39244046/201510768-cf722a15-8839-4b97-8971-9fac8a01ca0c.png)
3. 重新打开文档后页面边距会自适应。
![image](https://user-images.githubusercontent.com/39244046/201510816-f5d7e136-7203-42f6-9223-7edb542a23d8.png)

**Comment by GentooXu** [comment]
还有一个问题：在Windows下，不隐藏左侧面板，Win + →将思源笔记放到右侧1/2屏。搜索界面麻烦再优化一下，谢谢！
![image](https://user-images.githubusercontent.com/39244046/201512603-2d371d8f-efa1-4063-ab54-d01af0455ad4.png)

**Comment by royc01** [comment]
1、那个是js调整宽度的，应该手动拖动边框会调整，暂时优化不了
2、在一定宽度会变为上下排列，但是这个bug我复现不了，重新下载一次看看？

**Comment by GentooXu** [comment]
> 1、那个是js调整宽度的，应该手动拖动边框会调整，暂时优化不了 2、在一定宽度会变为上下排列，但是这个bug我复现不了，重新下载一次看看？

我的电脑分辨率是2880*1800，150%缩放，思源笔记居右占1/2屏幕的时候就会出现这种情况。

**Comment by royc01** [comment]
我笔记本也差不多这个参数，半屏是上下分栏，没毛病

**Comment by GentooXu** [comment]
> 我笔记本也差不多这个参数，半屏是上下分栏，没毛病

是上下分栏了，但是上栏占比过大，下栏占比过小了。同时，上线分栏的时候能否将上栏设置为宽度100%？
![image](https://user-images.githubusercontent.com/39244046/201594307-b32e490a-9a01-4b41-a979-e7438f87af2a.png)

**Comment by royc01** [comment]
我这边是这样显示的
<img width="556" alt="111" src="https://user-images.githubusercontent.com/38906705/201594689-fbfd7c78-7fb9-401d-aa4d-8a4ec00547a8.png">

**Comment by GentooXu** [comment]
好吧，好奇怪呀。我没有下载任何其他主题，外观主题重置都试过了，还是那个样子。。。

**Comment by royc01** [comment]
清除一下缓存试试？

**Comment by GentooXu** [comment]
试过了还是不行呀

**Comment by royc01** [comment]
这个就不好定位了。。看看其他小伙伴会不会有这样的问题

**Comment by GentooXu** [comment]
问题我找到了，我的电脑1/2屏刚好是960px的宽度，就使用了左右分栏。
![image](https://user-images.githubusercontent.com/39244046/201609617-29d96d89-ce59-464e-b5a9-51e4359c1b9f.png)
![image](https://user-images.githubusercontent.com/39244046/201610310-7bb12696-7df6-487d-a801-c2a2cb7d57ac.png)

**Comment by GentooXu** [comment]
我把css中的960改成961px就好了。

**Comment by royc01** [comment]
这么神奇吗😂，那我后面改一下

**Comment by GentooXu** [comment]
确实哈，谢谢大神了！
