### ISSUE TITLE
通过Ctrl+滚轮修改过的缩放无法恢复了

### ISSUE THREAD

**Issue by cesaryuan** [royc01/notion-theme#99]
在某一次通过Ctrl+滚轮修改过缩放之后，缩放就永远都恢复不了了，重启没有用

https://user-images.githubusercontent.com/35998162/201512847-5b2d7c7a-ace0-4c55-b9be-c5aac1bdf057.mp4

**Comment by royc01** [comment]
主题简介里面有的，使用开发者工具清除缓存可以复位
![8%Z37140%1S@147XH3OQ8%O](https://user-images.githubusercontent.com/38906705/201512959-81cbfa88-54b4-4845-a33e-4ec8dd317751.jpg)

**Comment by cesaryuan** [comment]
> 主题简介里面有的，使用开发者工具清除缓存可以复位 ![8%Z37140%1S@147XH3OQ8%O](https://user-images.githubusercontent.com/38906705/201512959-81cbfa88-54b4-4845-a33e-4ec8dd317751.jpg)

经测试，清除缓存方法无效


https://user-images.githubusercontent.com/35998162/201513164-57d291d0-dc22-4457-9f96-c80be0840229.mp4

**Comment by royc01** [comment]
你后面录屏的已经不是savor主题了，是不是设置-编辑器-字号改了

**Comment by cesaryuan** [comment]
> 你后面录屏的已经不是savor主题了，是不是设置-编辑器-字号改了

savor主题也试了下，还是一样。字号我吃饭饭回去看看
麻烦大佬啦

**Comment by cesaryuan** [comment]
我的锅，确实是编辑器字号改了，打扰大佬啦
